---
http_interactions:
- request:
    method: put
    uri: http://localhost:3200/source/home:backend_user/_meta?user=backend_user
    body:
      encoding: UTF-8
      string: |
        <project name="home:backend_user">
          <title/>
          <description/>
          <person userid="backend_user" role="maintainer"/>
        </project>
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - text/xml
      Cache-Control:
      - no-cache
      Connection:
      - close
      Content-Length:
      - '147'
    body:
      encoding: UTF-8
      string: |
        <project name="home:backend_user">
          <title></title>
          <description></description>
          <person userid="backend_user" role="maintainer" />
        </project>
    http_version: 
  recorded_at: Thu, 16 Jun 2016 14:38:41 GMT
- request:
    method: put
    uri: http://localhost:3200/source/backend_project/_meta?user=backend_user
    body:
      encoding: UTF-8
      string: |
        <project name="backend_project">
          <title>Finding a New Sun</title>
          <description/>
        </project>
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - text/xml
      Cache-Control:
      - no-cache
      Connection:
      - close
      Content-Length:
      - '109'
    body:
      encoding: UTF-8
      string: |
        <project name="backend_project">
          <title>Finding a New Sun</title>
          <description></description>
        </project>
    http_version: 
  recorded_at: Thu, 16 Jun 2016 14:38:41 GMT
recorded_with: VCR 3.0.1
