source 'http://rubygems.org'

gem 'rails', '2.3.14'
gem 'nokogiri', '~>1.5.0'
gem 'xmlhash', '=1.2.2'
gem 'exception_notification', '<1.1'
gem 'erubis'
gem 'rails_xss'
gem 'test-unit'
gem 'ci_reporter'
gem 'fast_xs'
gem 'webrat', '>=0.4.3'
gem 'sqlite3'

