#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

OBSWebUI::Application.load_tasks

require File.join(File.dirname(__FILE__), 'config', 'boot')

begin
  require 'ci/reporter/rake/minitest'
rescue LoadError
  puts "Please run 'rake gems:install' to install the 'ci_reporter' gem."
end

