FROM openbuildservice/base

RUN /root/bin/docker-bootstrap.sh memcached
RUN /root/bin/docker-bootstrap.sh backend
RUN /root/bin/docker-bootstrap.sh frontend

ADD Gemfile /obs/src/api/Gemfile
ADD Gemfile.lock /obs/src/api/Gemfile.lock
ADD docker-files/start_old_tests /obs/contrib/start_old_tests
RUN chown -R frontend:users /obs/

# Set up some convenience ruby binaries...
RUN for i in ruby gem irb; do ln -s /usr/bin/$i.ruby2.5 /usr/local/bin/$i; done

USER frontend
WORKDIR /obs/src/api

# Install our bundle
# FIXME: Retrying bundler if it fails is a workaround for https://github.com/moby/moby/issues/783
#        which seems to happen on openSUSE (< Tumbleweed 20171001)...
RUN export NOKOGIRI_USE_SYSTEM_LIBRARIES=1; bundle install --jobs=3 --retry=3 || bundle install --jobs=3 --retry=3

# Run our command
CMD ["/bin/bash", "-l"]
