FROM openbuildservice/frontend-base

RUN /root/bin/docker-bootstrap.sh memcached
RUN /root/bin/docker-bootstrap.sh backend

ADD --chown=frontend:users . /obs

USER frontend
WORKDIR /obs/src/api

# Refresh our bundle
RUN export NOKOGIRI_USE_SYSTEM_LIBRARIES=1; bundle install --jobs=3 --retry=3 || bundle install --jobs=3 --retry=3

# Run our command
CMD ["/bin/bash", "-l"]
