#!/bin/bash

echo "Installing bundle..."
export NOKOGIRI_USE_SYSTEM_LIBRARIES=1; bundle install --jobs=3 --retry=3 || bundle install --jobs=3 --retry=3

echo "Preparing application..."
bundle exec rake dev:bootstrap[old_test_suite] RAILS_ENV=test

echo "Running api test suite..."
export NO_MEMCACHED=1
bundle exec rake test:api
