#!/bin/bash
echo "Installing bundle..."
export NOKOGIRI_USE_SYSTEM_LIBRARIES=1; bundle install --jobs=3 --retry=3 --path vendor/bundle || bundle install --jobs=3 --retry=3 --path vendor/bundle
echo "Preparing application..."
bundle exec rake dev:bootstrap[old_test_suite] RAILS_ENV=test
echo "Running spider test..."
export NO_MEMCACHED=1
bundle exec rake test:spider
tmp_exit=$?
rm -rf .bundle vendor/bundle
exit $tmp_exit
