inherit_from: .rubocop_todo.yml

AllCops:
  UseCache: true
  CacheRootDirectory: src/api/tmp/rubocop_cache
  MaxFilesInCache: 2000
  Exclude:
    - 'src/api/tmp/**/*'
    - 'src/api/lib/templates/**/*'
    - 'src/api/vendor/bundle/**/*'
    - 'docs/api/restility/**/*'
    - 'src/api/test/fixtures/backend/**/*'
    - 'src/api/files/*'
    - 'dist/**/*'
    - 'src/backend/**/*'

#################### Layout ###########################

# Align the elements of a hash literal if they span more than one line.
Layout/AlignHash:
  # Alignment of entries using hash rocket as separator.
  EnforcedHashRocketStyle: table
  # Alignment of entries using colon as separator.
  EnforcedColonStyle: table
  # Select whether hashes that are the last argument in a method call should be
  # inspected?
  EnforcedLastArgumentHashStyle: ignore_implicit

# Alignment of parameters in multi-line method calls.
Layout/AlignParameters:
  EnforcedStyle: with_first_parameter

#################### Style ###########################

# Find uses of alias where alias_method would be more appropriate (or is simply preferred due to configuration), and vice versa.
# It also finds uses of alias :symbol rather than alias bareword.
Style/Alias:
  EnforcedStyle: 'prefer_alias_method'

# Use ` or %x around command literals.
Style/CommandLiteral:
  EnforcedStyle: percent_x

# Checks for chaining of a block after another block that spans multiple lines.
Style/MultilineBlockChain:
  Exclude:
    - 'src/api/spec/models/project_spec.rb'
    - 'src/api/spec/models/package_spec.rb'
    - 'src/api/spec/helpers/webui/package_helper_spec.rb'
    - 'src/api/spec/models/kiwi/repository_spec.rb'
    
# Checks for redundant `return` expressions
Style/RedundantReturn:
  Enabled: false

Style/GlobalVars:
  AllowedVariables: ['$rabbitmq_conn', '$rabbitmq_exchange', '$rabbitmq_channel']

##################### Metrics ##################################

# Checks if the length a class exceeds some maximum value
Metrics/ClassLength:
  Severity: refactor

# Checks the length of lines in the source code.
Metrics/LineLength:
  Max: 150
  IgnoredPatterns: ['\A#']

# Checks if the length a module exceeds some maximum value
Metrics/ModuleLength:
  Severity: refactor

##################### Lint ##################################

# Align ends correctly.
Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

# Checks for nested method definitions
Lint/NestedMethodDefinition:
  Exclude:
    - 'src/api/test/functional/tag_controller_test.rb'

##################### Rails ##################################

Rails:
  Enabled: true

# Enforces that 'exit' calls are not used.
Rails/Exit:
  Exclude:
    - 'src/api/lib/memory_dumper.rb'

# Requires each table column to have a default value
Rails/NotNullColumn:
  Exclude:
    - 'src/api/db/migrate/20121121142111_watchlist_use_ids.rb'
    - 'src/api/db/migrate/20131020151037_make_comment_users_ids.rb'
    - 'src/api/db/migrate/20131027122410_add_primary_to_repository_architectures.rb'
    - 'src/api/db/migrate/20131209103450_add_primary_to_groups_users.rb'

# Checks for the use of output calls like puts and print
Rails/Output:
  Exclude:
    - 'src/api/app/jobs/*'
    - 'src/api/config/*'
    - 'src/api/db/**/*'
    - 'src/api/lib/**/*'

# Checks for the use of methods which skip validations.
Rails/SkipsModelValidations:
  Exclude:
    - 'src/api/db/migrate/*'
    - 'src/api/app/jobs/*'
    - 'src/api/spec/models/bs_request_action_spec.rb'
    - 'src/api/spec/models/review_spec.rb'
