language: ruby
cache: bundler
rvm: 2.3.0
gemfile: src/api/Gemfile
before_install: dist/ci/obs_testsuite_travis_install.sh
before_script: dist/ci/obs_testsuite_travis_before.sh
script: "dist/ci/obs_testsuite_travis.sh $TEST_SUITE"
env:
  - TEST_SUITE=rubocop
  - TEST_SUITE=api
  - TEST_SUITE=webui
  - TEST_SUITE=spider
  - TEST_SUITE=rspec
matrix:
  fast_finish: true
notifications:
  irc:
     channels:
       - "chat.freenode.net#opensuse-buildservice"
     on_success: change
     on_failure: change  
services:
  - memcached
sudo: required
addons:
  artifacts: true
  s3_region: "us-east-1"
  paths:
    - $(ls ./src/api/log/*.log | tr "\n" ":")
    - $(ls -R ./src/api/tmp/capybara/ | tr "\n" ":")
