# Machine config
dist: trusty
sudo: required
services:
  - docker

# Language and app config
language: ruby

cache:
  directories:
    - src/api/vendor/bundle
# Github config
branches:
  except:
    # starting with depfu/
    - /^depfu\/.*/

# Scripts
after_failure: dist/ci/travis_after_failure.sh
 # we need to chown the build dir to frontend:users (1000:100) to avoid permission errors
before_script: sudo chown 1000:100 $TRAVIS_BUILD_DIR -R
script: "dist/ci/travis_script.sh $TEST_SUITE"

env:
  global: 
  - TEST_SUITE=rspec
