# Machine config
dist: trusty
sudo: required
services:
  - docker

# Language and app config
language: ruby
rvm: 2.5.0

# Github config
branches:
  except:
    # starting with depfu/
    - /^depfu\/.*/

# Scripts
before_script: dist/ci/travis_before_script.sh
after_failure: dist/ci/travis_after_failure.sh
script: "dist/ci/travis_script.sh $TEST_SUITE"

# Notifications
notifications:
  irc:
     channels:
       - "chat.freenode.net#opensuse-buildservice"
     on_success: change
     on_failure: change

# Jobs matrix and stages 
jobs:
  include:
    - stage: Linters
      env: TEST_SUITE=linter
      cache:
        bundler: true
        directories:
          - tmp/rubocop_cache
    - stage: test
      env: TEST_SUITE=rspec
    - env: TEST_SUITE=api
    - env: TEST_SUITE=spider
    - env: TEST_SUITE=backend
  fast_finish: true
