fixes:
  - "::src/api/"
codecov:
  ci:
    - !travis-ci.org
  notify:
    require_ci_to_pass: yes
coverage:
  status:
    project:
      default:
        target: 88.5
comment:
  layout: "reach, diff, flags"
  require_changes: true
