fixes:
  - "::src/api/"
codecov:
  ci:
    - !travis-ci.org
coverage:
  status:
    project:
      default:
        target: auto
        base: auto
        threshold: 1
comment:
  layout: "reach, diff, flags"
  require_changes: true
