# See docs.getsentry.com/on-premise/server/ for full instructions

version: '2.1'

x-defaults: &defaults
  # build: docker-files/sentry
  image: sentry:9.0
  depends_on:
    - redis
    - postgres
    - memcached
    - smtp

  environment:
    # Run `docker-compose run web config generate-secret-key`
    # to get the SENTRY_SECRET_KEY value.
    SENTRY_SECRET_KEY: 'supersecret'
    SENTRY_MEMCACHED_HOST: memcached
    SENTRY_REDIS_HOST: redis
    SENTRY_POSTGRES_HOST: postgres
    SENTRY_EMAIL_HOST: smtp
  # For your own environment variables that shouldn't end up in git...
  env_file: docker-files/sentry/env

  volumes:
    - sentry-data:/var/lib/sentry/files


services:
  smtp:
    image: tianon/exim4

  memcached:
    image: memcached:1.4

  redis:
    image: redis:3.2-alpine

  postgres:
    image: postgres:9.5
    volumes:
      - sentry-postgres:/var/lib/postgresql/data

  web:
    <<: *defaults
    ports:
      - '9000:9000'

  cron:
    <<: *defaults
    command: run cron

  sentry-worker:
    <<: *defaults
    command: run worker

volumes:
    sentry-data:
    sentry-postgres:
