version: "2.1"
services:
  db:
    image: registry.opensuse.org/obs/server/unstable/container/leap/42.3/images/openbuildservice/mariadb:latest
    ports:
      - "3306:3306"
  cache:
    image: registry.opensuse.org/obs/server/unstable/container/leap/42.3/images/openbuildservice/memcached:latest
    ports:
      - "11211:11211"
  backend:
    image: registry.opensuse.org/obs/server/unstable/container/leap/42.3/images/openbuildservice/backend:latest
    volumes:
      - .:/obs
      - ./dist/aws_credentials:/etc/obs/cloudupload/.aws/config
      - ./dist/ec2utils.conf:/etc/obs/cloudupload/.ec2utils.conf
      - ./dist/clouduploader.rb:/usr/bin/clouduploader
    command: /obs/contrib/start_development_backend -d /obs
  worker:
    image: registry.opensuse.org/obs/server/unstable/container/leap/42.3/images/openbuildservice/backend:latest
    volumes:
      - .:/obs
    privileged: true
    depends_on:
      - backend
    command: /obs/contrib/start_development_worker
  frontend:
    image: registry.opensuse.org/obs/server/unstable/container/leap/42.3/images/openbuildservice/frontend-base:latest
    build:
      dockerfile: docker-files/Dockerfile
      context: src/api
    volumes:
      - .:/obs
    ports:
      - "3000:3000"
      - "1080:1080"
    depends_on:
      - db
      - cache
      - backend
      - worker
