version: "2.1"
services:
  db:
    image: registry.opensuse.org/obs/server/unstable/containers/containers/openbuildservice/mariadb
    ports:
      - "3306:3306"
    command: /usr/lib/mysql/mysql-systemd-helper start
  cache:
    image: registry.opensuse.org/obs/server/unstable/containers/containers/openbuildservice/memcached
    ports:
      - "11211:11211"
    command: /usr/sbin/memcached -u memcached
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass opensuse
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
  backend:
    image: registry.opensuse.org/obs/server/unstable/containers/containers/openbuildservice/backend
    volumes:
      - .:/obs:z
      - ./dist/aws_credentials:/etc/obs/cloudupload/.aws/config:Z
      - ./dist/ec2utils.conf:/etc/obs/cloudupload/.ec2utils.conf:Z
      - ./dist/clouduploader.rb:/usr/bin/clouduploader:Z
    command: /obs/contrib/start_development_backend -d /obs
  worker:
    image: registry.opensuse.org/obs/server/unstable/containers/containers/openbuildservice/backend
    volumes:
      - .:/obs:z
    privileged: true
    depends_on:
      - backend
    command: /obs/contrib/start_development_worker
  frontend:
    image: openbuildservice/frontend
    command: foreman start -p 3000
    build:
      dockerfile: docker-files/Dockerfile
      context: src/api
      args:
        CONTAINER_USERID: 1000
    volumes:
      - .:/obs:z
    ports:
      - "3000:3000"
      - "1080:1080"
    depends_on:
      - db
      - cache
      - backend
      - worker
      - redis
