#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/boot'

if ENV["DO_COVERAGE"]
  require 'simplecov'
  require 'simplecov-rcov'
  SimpleCov.command_name "server"
  # check .simplecov for details
  SimpleCov.start 'rails'
end

require 'commands/server'
