#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/boot'

if ENV["DO_COVERAGE"]
  require 'simplecov'
  require 'simplecov-rcov'
  SimpleCov.start 'rails'
  
  class SimpleCov::Formatter::MergedFormatter
    def format(result)
      SimpleCov::Formatter::HTMLFormatter.new.format(result)
      if ENV["DO_COVERAGE"] == "rcov"
        SimpleCov::Formatter::RcovFormatter.new.format(result)
      end
    end
  end
  
  SimpleCov.formatter = SimpleCov::Formatter::MergedFormatter
end

require 'commands/server'
