openapi: 3.0.0

servers:
  - url: '/'

tags:
  - name: General Information

info:
  description: Open Build Service API
  version: '2.10.50'
  title: Open Build Service API
  contact:
    url: 'https://openbuildservice.org/'
    name: Open Build Service
  license:
    url: 'https://github.com/openSUSE/open-build-service/blob/master/COPYING'
    name: GNU General Public License v2.0

paths:
  /about:
    get:
      summary: Get information about API.
      description: Get generic information about the API.
      responses:
        '200':
          description: OK. The request has succeeded.
          content:
            application/xml; charset=utf-8:
              schema:
                $ref: '#/components/schemas/about'
      tags:
        - General Information

components:
  schemas:
    about:
      type: object
      properties:
        title:
          type: string
          example: Open Build Service API
        description:
          type: string
          example: API to the Open Build Service
        revision:
          type: string
          example: '2.11~alpha.20201110T101235.7b5d82e614'
        last_deployment:
          type: string
          example: '2020-11-10 15:07:02 +0000'
        commit:
          type: string
          example: '7b5d82e6143442a8eb8459f35cc94d2fbe263ebe'
externalDocs:
  url: 'https://openbuildservice.org/help/'
  description: Open Build Service - Documentation
