# Edit this Gemfile to bundle your application's dependencies.
# This preamble is the current preamble for Rails 3 apps; edit as needed.
source 'http://rubygems.org'

gem 'selenium-webdriver'
gem 'headless'
gem 'colored'
# in compliance with rails - better not require builder-3.1
gem 'builder', '~> 3.0.0'

# it's only used for jenkins, but we better track it somewhere
gem 'flog'
