# Edit this Gemfile to bundle your application's dependencies.
# This preamble is the current preamble for Rails 3 apps; edit as needed.
source 'http://rubygems.org'

gem 'selenium-webdriver'
gem 'headless'
gem 'colored'
gem 'builder'

