#!/usr/bin/perl -w
#
# Copyright (c) 2008 Klaas Freitag, Novell Inc.
# Copyright (c) 2008 Adrian Schroeter, Novell Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program (see the file COPYING); if not, write to the
# Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA
#
################################################################
#
# Converter to create Kiwi- and Spec files from product definition
#
use strict;
use Getopt::Std;
use Data::Dumper;

use XML::Structured ':bytes';
use BSUtil;
use BSProductXML;
use BSKiwiXML;


# read the product xml file

use vars qw ( $opt_h @errors %groupRefs );

sub usage()
{
  print<<END

  bs_productconvert

  convert a product definition file to a spec- and a kiwi source file.

  Options:

  -h:   help, print this text.

END
;

  exit;
}

sub readProductFile( $ )
{
    my ($filename) = @_;

    print "parsing product definition... ";
    my $xml = BSProductXML::readproductxml( "$filename", 0 );

    if( defined($xml) ) {
	print "success!\n";
    } else {
	print "FAILED: Unable to parse $filename\n";
	die;
    }
    return $xml;
}


sub createDescription( $ )
{
    my( $prodRef ) = @_;
    my $re;

    $re->{type} = "system";
    $re->{author} = "The SUSE Team";
    $re->{contact} = "build\@opensuse.org";
    $re->{specification} = $prodRef->{general}->{summary}[0]->{_content};

    return $re;
}

sub createPreferences( $ )
{
    my( $prodRef ) = @_;
    my $re = {};

    $re->{type} = [{_content => "dummy"}];
    $re->{version} = sprintf( "%s.%s",
			      $prodRef->{general}->{version},
			      $prodRef->{general}->{release}  );

    # $re->{size} = ; do not give the optional size
    $re->{packagemanager} = "zypper" ;

    return $re;
}

sub createArchitectures()
{
    my $re = {};

    my $archfallbacks = { 'ppc64' => { name => 'Motorola 64 Bit', fallback => 'ppc' },
			  'ppc' =>   { name => 'Motorola 32 Bit', fallback => 'noarch' },
			  'i686' =>  { name => 'Intel x86', fallback => 'i586' },
			  'i586' =>  { name => 'Intel x86', fallback => 'i486' },
			  'i486' =>  { name => 'Intel x86', fallback => 'i386' },
			  'i386' =>  { name => 'Intel x86', fallback => 'noarch' },
			  'x86_64' =>{ name => 'AMD 64 bit', fallback => 'i686' },
			  'src'  =>  { name => 'Source rpms', fallback => undef } };
    my @archs;
    foreach my $arch ( keys %$archfallbacks ) {
	my %h;
	$h{id} = $arch;
	$h{name} = $archfallbacks->{$arch}->{name};
	$h{fallback} = $archfallbacks->{$arch}->{fallback} if( $archfallbacks->{$arch}->{fallback});
	push @archs, \%h;
    }
    $re->{arch} = \@archs;

    my @reqXml;
    my @reqArchs = ( 'ppc64', 'ppc', 'i686', 'x86_64' ); # We need to specify in PD which architectures should
                                                         # be used and in which combination.
    foreach ( @reqArchs ) {
	my %h;
	$h{ref} = $_;
	push @reqXml, \%h;
    }
    $re->{requiredarch} = \@reqXml;

    return $re;
}

sub createProductOptions()
{
    my $re = {};
    my %options;

    $options{PRODUCT_THEME} = "SuSE";
    $options{MEDIUM_NAME} = "FTP";
    $options{MULTIPLE_MEDIUM} = "no";
    $options{SHA1_OPT} = "-x";
    # add more as needed.
    my @vars;
    foreach my $opt ( keys %options ) {
	push @vars, { name => $opt, _content => $options{$opt} };
    }

    $re->{productvar} = \@vars;

    my %info;
    $info{'ARCH.x86_64'} = "x86_64 i686 i586 i486 i386 noarch";
    $info{'ARCH.ppc64'}  = "ppc64 ppc noarch";
    $info{'ARCH.ppc'}    = "ppc noarch";
    $info{'ARCH.i686'}   = "i686 i586 i486 i386 noarch";
    $info{'ARCH.i586'}   = "i586 i486 i386 noarch";
    $info{'ARCH.i486'}   = "i486 i386 noarch";
    $info{'ARCH.i386'}   = "i386 noarch";
    $info{'DEFAULTBASE'} = "i586";
    # add more ...
    my @info;
    foreach my $opt ( keys %info) {
	push @info, { name => $opt, _content => $info{$opt} };
    }

    $re->{productinfo} = \@info;

    return $re;

}

sub createMetadata( $$ )
{
    my( $prodRef, $medium ) = @_;
    
    return undef unless( $medium->{'metadata'} );
    my $re = {};

    # print "> " . Dumper $medium->{metadata};

    my @packages;
    my @files;
    foreach my $pack ( @{ $medium->{metadata}->{package} } ) {
	push @packages, { name => $pack->{name}, 
			  medium => "0", 
			  removearch => "src" };
    }

    my @a;
    return { repopackage => \@packages };
    
#     my @files;
#     foreach my $file ( @{ $medium->{metadata}->{file} } ) {
# 	push @files, { name => $file->{name} };
#     }
#     # push @a, { file => \@files }; CHECK: Needed?
# 
#     return \@a;
}

sub useToPackages( $$ )
{
    my ($prodRef, $medium ) = @_;

    return unless $medium;
    
    return unless $medium->{use};
    my @useStatements = @{$medium->{use} };

    my @packages;

    foreach my $useState ( @useStatements ) {

	my $useRequired = $useState->{use_required};
	my $useSuggested = $useState->{use_suggested};
	my $useRecommended = $useState->{use_recommended};

	if( $useState->{group} ) {
	    push @packages, groupToPackages( $useState->{group}, 
					     $useRequired, 
					     $useRecommended, 
					     $useSuggested );
	    # there might be additional packages listed in the group.
	    if( $useState->{package} ) {
		foreach my $addPack ( @{$useState->{package} } ) {
		    # print Dumper( $addPack ) . "\n";
		    if( ( $useRequired    && $addPack->{relationship} eq "required") ||
			( $useRecommended && $addPack->{relationship} eq "recommended" ) ||
			( $useSuggested   && $addPack->{relationship} eq "suggested" ) ) {
 
			push @packages, { name => $addPack->{name} };
		    }
		}
	    }
	} elsif( $useState->{pattern} ) {
# 	    push @packages, PatternToPackages( $useState->{pattern}, 
# 					       $useRequired, 
# 					       $useRecommended, 
# 					       $useSuggested );
# 	    
	}
    }
    return \@packages;
}

sub groupToPackages( $$$$ ) 
{
    my ($group, $useReq, $useRec, $useSug ) = @_;

    my $groupsBaseDir = "testdata/productdefinition";
    my $file = "$groupsBaseDir/groups/$group.xml";
    unless( -r $file ) {
	print "ERR: Could not find group definition named <$file>\n";
	return ();
    }

    my $groupRef;

    unless( $groupRefs{$group} ) {

	$groupRef = readxml( $file, $BSProductXML::group );
	$groupRefs{$group} = $groupRef;
	    
	expandPackages( $groupRef );
    }
    $groupRef = $groupRefs{$group};
    
    my @resultList;
    if( $useReq && $groupRef->{_required} ) {
	push @resultList, @{$groupRef->{_required}};
    } 
    if( $useRec && $groupRef->{_recommended}) {
	push @resultList, @{$groupRef->{_recommended}};
    } 
    if( $useSug && $groupRef->{_suggested} ) {
	push @resultList, @{$groupRef->{_suggested}};
    } 

    return @resultList;
}

#
# This sub expands the patterns 
sub expandPackages( $ )
{
    my ($groupRef) = @_;
    
    my $name = $groupRef->{name};

    print "Working on group $name\n";
    
    my @patterns = @{$groupRef->{pattern}};
    
    my $pat = @{$groupRef->{pattern}}[0];
    $groupRef->{_pattern} = $pat;


    foreach my $pack ( @{$groupRef->{group}} ) {
	my $packListRef = $pack->{package};
	my $relation = $pack->{relationship};
	my @resultPacks;
	foreach my $packRef ( @${packListRef} ) {
	    print "Pushing $packRef->{name}\n";
	    push @resultPacks, { name => $packRef->{name} }; 
	}
	my $keyname = "_" . lc $relation;
	print "Keyname of package list: $keyname\n";
	$groupRef->{$keyname} = \@resultPacks;
    }
}

sub createInstsource( $$ )
{
    my( $prodRef, $medium ) = @_;
    my $re = {};

    $re->{architectures} = createArchitectures();
    $re->{productoptions} = createProductOptions();
    # instrepo can be copied, but lets check if only obs:// is used.
    my @r;
    foreach my $repo ( @{$prodRef->{instrepo}} ){
      die "ERROR: Non obs:// repo used in $repo->{'name'}\n" if ( $repo->{'source'}->{'path'} !~ "^obs://.+" );
      push @r, $repo;
    }
    # Hm, should we implicit add our own Project ?
    $re->{instrepo} = \@r;
    
    # metadata, media dependant
    my $ref = createMetadata( $prodRef, $medium );
    if( $ref ) {
	$re->{metadata} = createMetadata( $prodRef, $medium );
    }

    # repopackages
    my @packages;
    my $useToPacks = useToPackages( $prodRef, $medium );
    if( $useToPacks ) {
	push @packages, { repopackage => $useToPacks };
    }
    # print "Packlist: " . Dumper \@packages;
    $re->{repopackages} =  \@packages;

    return $re;
}

sub createRepository
{
    # This is for a dummy entry, it is required by the kiwi DTD, but not used
    # for installation medias.
    my( $prodRef ) = @_;
    my @repository;
    my $source;
    my $dummydir = "/var/lib/empty";

    # Do we have ever a different repo type than "yast" on products ?
    $source->{ 'path' } = $dummydir;
    push @repository, { 'type' => 'yast2', 'source' => $source };

    return \@repository;
}

sub writeProductFile
{
    my( $file, $prodRef ) = @_;

}

sub writeProductSPECfile
{
    my( $file, $infile, $prodRef ) = @_;

    my $product_flavors="";
    foreach my $flavor ( @{$prodRef->{mediasets}->{media}} ){
      $product_flavors.="%package $flavor->{type}\n";
      $product_flavors.="%define flavor $flavor->{type}\n";
      $product_flavors.="License:        BSD 3-Clause\n";
      $product_flavors.="Group:          System/Fhs\n";
      $product_flavors.="Summary:        $prodRef->{general}->{summary}[0]->{_content}\n"; #FIXME: search for non-lang 
      $product_flavors.="\n";
      $product_flavors.="%description $flavor->{type}\n";
      $product_flavors.="$prodRef->{general}->{description}[0]->{_content}\n"; #FIXME: search for non-lang 
      $product_flavors.="\n";
      $product_flavors.="%files $flavor->{type}\n";
      $product_flavors.="%defattr(-,root,root)\n";
      $product_flavors.="%dir /etc/products.d\n";
      $product_flavors.="/etc/products.d/$prodRef->{general}->{name}-$flavor->{type}.prod\n";
      $product_flavors.="\n"
    }

    my $zypp_product_file = "";
    $zypp_product_file = "mkdir -p \$RPM_BUILD_ROOT/etc/products.d\n";
    foreach my $flavor ( @{$prodRef->{mediasets}->{media}} ){
      my $pfile = "\$RPM_BUILD_ROOT/etc/products.d/$prodRef->{general}->{name}-$flavor->{type}.prod";
#   INI file syntax
#      $str = "${str}echo -e \"[product]\" > $pfile\n";
#      $str = "${str}echo -e \"name = %{product}\" >> $pfile\n";
#      $str = "${str}echo -e \"version = %{version}-%{release}\" >> $pfile\n";
#      $str = "${str}#%{arch} doesn't expand ?!\n";
#      $str = "${str}#echo -e \"arch = %{arch} \ >> $pfile\n";
#      $str = "${str}echo -e \"flavor = %{flavor}\" >> $pfile\n";
#      $str = "${str}echo -e \"distribution = %{distribution}\" >> $pfile\n";
#      $str = "${str}echo -e \"vendor = %{vendor}\" >> $pfile\n";
#      $str = "${str}echo -e \"\" >> $pfile\n";
#      $str = "${str}echo -e \"[translated]\" >> $pfile\n";
#      foreach my $element ( "summary", "description" ){
#        foreach my $text ( @{$prodRef->{general}->{$element}} ){
#          $str = "$str\n echo -e \"$element";
#          $str = "$str\[$text->{lang}\]" if ( $text->{lang} );
#          $str = "$str = $text->{_content}\" >> $pfile\n";
#        }
#      }

#   XML file syntax
      my $product;
      $product->{'general'} = $prodRef->{general};
      $product->{'schemeversion'} = "0.0"; # FIXME: moving target, still in development.
      my $d = {};
      $d->{'type'} = $flavor->{type};
      $d->{'flavor'} = "build.suse.de_SUSE_Factory_HEAD-%arch"; # FIXME
      $product->{'general'}->{'distribution'} = $d;

      my $xml = XMLout( $BSProductXML::productdesc, $product );
      $xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n$xml";
      die ( "ERROR: Unable to create xml for $flavor->{type} !" ) unless $xml;
      $zypp_product_file .= "cat >$pfile << EOF\n";
      $zypp_product_file .= "$xml\nEOF\n\n";
    }

    my $str='';
    # read template file
    local *IF;
    if (!open(IF, '<', $infile)) {
      die("$infile: $!\n");
    }
    1 while sysread(IF, $str, 8192, length($str));
    close IF;

    # replace all strings
    $str =~ s/___VERSION___/$prodRef->{general}->{version}/g;
    $str =~ s/___BETA_VERSION___/$prodRef->{general}->{buildconfig}->{betaversion}/g;
    $str =~ s/___RELEASE___/0/g;
    $str =~ s/___PACKAGE_NAME___/$prodRef->{general}->{name}-release/g;
    $str =~ s/___PRODUCT_NAME___/$prodRef->{general}->{name}/g;
    $str =~ s/___SUMMARY___/$prodRef->{general}->{summary}[0]->{_content}/g; # FIXME: find the non-lang one
    $str =~ s/___DESCRIPTION___/$prodRef->{general}->{description}[0]->{_content}/g; # FIXME: find the non-lang one
    $str =~ s/___FLAVOR_PACKAGES___/$product_flavors/g;
    $str =~ s/___CREATE_PRODUCT_FILES___/$zypp_product_file/g;

    # write out the modified file.
    local *OF;
    open(OF, '>', $file) || die("$file: $!\n");
    (syswrite(OF, $str) || 0) == length($str) || die("$file write: $!\n");
    close(OF) || die("$file close: $!\n");
}

# Process the commandline arguments.
getopts('h');

usage() if ($opt_h );

my ($infile) = @ARGV;

die( "Please specify input file" ) unless $infile;

my $prodRef = readProductFile( $infile );

#
# Create a kiwi configuration for each distribution flavor
#

my $kiwiImage;
$kiwiImage->{schemeversion} = "2.4"; # ???
my $name = sprintf( "%s %s %s, Rel. %s",
		    $prodRef->{general}->{vendor},
		    $prodRef->{general}->{name},
		    $prodRef->{general}->{version},
		    $prodRef->{general}->{release} );

$kiwiImage->{name} = $name;

$kiwiImage->{description} = createDescription( $prodRef );
$kiwiImage->{preferences} = createPreferences( $prodRef );
# so far for all media types identical. Now loop over the media types
# to create media type specific versions;

my %generalImage = %{$kiwiImage};

my $media = $prodRef->{mediasets}->{media};

foreach my $medium ( @$media ){
    my $type = $medium->{type};
    my $kiwi = \%generalImage;

    $kiwi->{instsource}  = createInstsource ( $prodRef, $medium );
    $kiwi->{repository}  = createRepository ( $prodRef );

    my $outFile = "$prodRef->{general}->{name}-$type.kiwi";

    writexml( "$outFile$$", $outFile, $kiwi, $BSKiwiXML::kiwidesc );
    print "$outFile written.\n";
}

#
# Create $product-release packages
#

#writeProductFile( "product.file", $prodRef );
my $templateFile;
if ($infile =~ /(.*\/)(.+)$/) {
    $templateFile = "$1/release.spec";
};
if ( -e "$templateFile" ) {
  writeProductSPECfile( "$prodRef->{general}->{name}-release.spec", $templateFile, $prodRef );
} else {
  print "No release template file $templateFile does exist.\nSPEC file generation skipped !\n";
};





# end
