#!/usr/bin/perl

die("Usage: bs_serverstatus <statusfile>\n") unless $ARGV[0];
open(STA, '<', $ARGV[0]) || die("$ARGV[0]: $!\n");
my $now = time();
my $sta;
my $empty = '';
while ((sysread(STA, $sta, 256) || 0) == 256) {
  my ($ti, $pid, $state, $data) = unpack("NNNZ244", $sta);
  if ($state == 0) {
    $empty .= " -\n";
    next;
  }
  my $d = $now - $ti;
  if ($state == 1) {
    $state = 'F';
  } elsif ($state == 2) {
    $state = 'R';
  } else {
    $state = '?';
  }
  printf "%s%s %3d %5d %s\n", $empty, $state, $d, $pid, $data;
  $empty = '';
}
close STA;
