# Task to update distributions list in initializers/anitya.rb

namespace :anitya do
  desc 'Update the Anitya distribution list in the initializer'
  task update_distros: :environment do
    url = 'https://release-monitoring.org/api/distro/names'
    initializer_path = Rails.root.join('config/initializers/anitya.rb')

    puts "Fetching latest distribution names from #{url}..."

    response = Net::HTTP.get(URI(url))
    distros = JSON.parse(response)['distro'].sort

    formatted_list = distros.map { |d| "'#{d.gsub("'", "\\\\'")}'" }.each_slice(8).map do |slice|
      "  #{slice.join(', ')}"
    end.join(",\n")

    File.open(initializer_path, 'w') do |f|
      f.puts "# This file is automatically generated by 'rake anitya:update_distros'"
      f.puts "# Last updated: #{Time.current}"
      f.puts "ANITYA_DISTROS = [\n#{formatted_list}\n].freeze"
    end

    puts "Successfully updated #{initializer_path} with #{distros.size} distributions."
  end
end
