# Install all web and api parts. (Remove parts in rules file)
# docs/api/html                 /srv/www/obs/api/public/apidocs/
# install apidocs
# the html dir was not found in source.
docs/api/api/*.{rng,xsd}        /srv/www/obs/docs/api/
src/api                                /srv/www/obs/
etc/logrotate.d/obs-api
srv/www/obs/api/
srv/www/obs/docs/api/
/usr/sbin/rcobsapidelayed
/usr/sbin/rcobsapisetup
etc/init.d/obsapisetup
etc/init.d/obsapidelayed
