# Install all web and api parts. (Remove parts in rules file)
# docs/api/html                 /srv/www/obs/api/public/apidocs/
# install apidocs
# the html dir was not found in source.
src/api                                /srv/www/obs/
docs/api/api/*.rng        /srv/www/obs/docs/api/
docs/api/api/*.xsd        /srv/www/obs/docs/api/
etc/logrotate.d/obs-api
srv/www/obs/api/
srv/www/obs/docs/api/
/usr/sbin/rcobsapidelayed
/usr/sbin/rcobsapisetup
etc/init.d/obsapisetup
etc/init.d/obsapidelayed
