#!/bin/bash


daemon=$1
obsdir=$2
logdir=$3

echo $daemon
echo $obsdir
echo $logdir

if [ -z "$daemon" -o -z "$obsdir" -o -z "$logdir" ]; then
  echo "Missing argument"
  exit 1
fi

LOG=$(echo $daemon | sed 's/^bs_//g')

cd "$obsdir"
exec "$obsdir"/$daemon >> "$logdir"/$LOG.log 2>&1
