linters:
  LineLength:
    max: 150

  # Apply lint in all partials, but exclude 'breadcrumb_items' partials
  InstanceVariables:
    enabled: true
    file_types: not_breadcrumb_items
    matchers:
      not_breadcrumb_items: \A_(?!breadcrumb_items).*\.haml\z

  RuboCop:
    enabled: true
    # These cops are incredibly noisy when it comes to HAML templates, so we
    # ignore them.
    ignored_cops:
      - Lint/BlockAlignment
      - Lint/EndAlignment
      - Lint/Void
      - Layout/ParameterAlignment
      - Layout/ElseAlignment
      - Layout/EndOfLine
      - Layout/IndentationWidth
      - Layout/TrailingEmptyLines
      - Layout/TrailingWhitespace
      - Layout/HashAlignment
      - Metrics/BlockLength
      - Metrics/BlockNesting
      - Layout/LineLength
      - Naming/FileName
      - Style/FrozenStringLiteralComment
      - Style/IfUnlessModifier
      - Style/Next
      - Style/WhileUntilModifier

exclude:
- 'vendor/bundle/**/*'
# The old staging workflow is still using Bento, so we don't lint it
- 'app/views/webui/theme/bento/**/*'
# Kaminari views were created by its generator, they don't pass lint tests
- 'app/views/webui/kaminari/**/*'
# Everything below is the API, we don't lint it (it's mostly XML anyway)
- 'app/views/about/**/*'
- 'app/views/attribute/**/*'
- 'app/views/attribute_namespace/**/*'
- 'app/views/build/**/*'
- 'app/views/comments/**/*'
- 'app/views/distributions/**/*'
- 'app/views/exception_notifier/**/*'
- 'app/views/group/**/*'
- 'app/views/ichain_notifier/**/*'
- 'app/views/message/**/*'
- 'app/views/models/**/*'
- 'app/views/person/**/*'
- 'app/views/public/**/*'
- 'app/views/request/**/*'
- 'app/views/result/**/*'
- 'app/views/search/**/*'
- 'app/views/shared/**/*'
- 'app/views/source/**/*'
- 'app/views/source_project/**/*'
- 'app/views/statistics/**/*'
- 'app/views/status/**/*'