linters:
  LineLength:
    max: 150

  # Apply lint in all partials, but exclude 'breadcrumb_items' partials
  InstanceVariables:
    enabled: true
    file_types: not_breadcrumb_items
    matchers:
      not_breadcrumb_items: \A_(?!breadcrumb_items).*\.haml\z

  RuboCop:
    enabled: true
    # These cops are incredibly noisy when it comes to HAML templates, so we
    # ignore them.
    ignored_cops:
      - Lint/BlockAlignment
      - Lint/EndAlignment
      - Lint/Void
      - Layout/AlignParameters
      - Layout/ElseAlignment
      - Layout/EndOfLine
      - Layout/IndentationWidth
      - Layout/TrailingBlankLines
      - Layout/TrailingWhitespace
      - Layout/AlignHash
      - Metrics/BlockLength
      - Metrics/BlockNesting
      - Metrics/LineLength
      - Naming/FileName
      - Style/FrozenStringLiteralComment
      - Style/IfUnlessModifier
      - Style/Next
      - Style/WhileUntilModifier

exclude:
- 'vendor/bundle/**/*'
# Everything below is the old interface. We only lint the new Bootstrap interface
- 'app/views/about/**/*'
- 'app/views/attribute/**/*'
- 'app/views/attribute_namespace/**/*'
- 'app/views/build/**/*'
- 'app/views/comments/**/*'
- 'app/views/distributions/**/*'
- 'app/views/exception_notifier/**/*'
- 'app/views/group/**/*'
- 'app/views/ichain_notifier/**/*'
- 'app/views/layouts/webui/**/*'
- 'app/views/message/**/*'
- 'app/views/models/**/*'
- 'app/views/person/**/*'
- 'app/views/public/**/*'
- 'app/views/request/**/*'
- 'app/views/result/**/*'
- 'app/views/search/**/*'
- 'app/views/shared/**/*'
- 'app/views/source/**/*'
- 'app/views/source_project/**/*'
- 'app/views/statistics/**/*'
- 'app/views/status/**/*'
- 'app/views/webui/**/*'
# Kaminari views were created by its generator, they don't pass lint tests
- 'app/views/webui2/webui/kaminari/**/*'
