linters:
  LineLength:
    max: 150

  # Apply lint in all partials, but exclude 'breadcrumb_items' partials
  InstanceVariables:
    enabled: true
    file_types: not_breadcrumb_items
    matchers:
      not_breadcrumb_items: \A_(?!breadcrumb_items).*\.haml\z

exclude:
- 'vendor/bundle/**/*'
# Everything below is the old interface. We only lint the new Bootstrap interface
- 'app/views/about/**/*'
- 'app/views/attribute/**/*'
- 'app/views/attribute_namespace/**/*'
- 'app/views/build/**/*'
- 'app/views/comments/**/*'
- 'app/views/distributions/**/*'
- 'app/views/event_mailer/**/*'
- 'app/views/exception_notifier/**/*'
- 'app/views/group/**/*'
- 'app/views/ichain_notifier/**/*'
- 'app/views/layouts/**/*'
- 'app/views/main/**/*'
- 'app/views/message/**/*'
- 'app/views/models/**/*'
- 'app/views/person/**/*'
- 'app/views/public/**/*'
- 'app/views/request/**/*'
- 'app/views/result/**/*'
- 'app/views/search/**/*'
- 'app/views/shared/**/*'
- 'app/views/source/**/*'
- 'app/views/source_project/**/*'
- 'app/views/statistics/**/*'
- 'app/views/status/**/*'
- 'app/views/webui/**/*'
