inherit_from: .rubocop_todo.yml

AllCops:
  UseCache: true
  CacheRootDirectory: tmp/rubocop_cache
  MaxFilesInCache: 2000
  Exclude:
    - 'tmp/**/*'
    - 'lib/templates/**/*'
    - 'vendor/bundle/**/*'

# Align the elements of a hash literal if they span more than one line.
Style/AlignHash:
  # Alignment of entries using hash rocket as separator.
  EnforcedHashRocketStyle: table
  # Alignment of entries using colon as separator.
  EnforcedColonStyle: table
  # Select whether hashes that are the last argument in a method call should be
  # inspected?
  EnforcedLastArgumentHashStyle: ignore_implicit

# Alignment of parameters in multi-line method calls.
Style/AlignParameters:
  EnforcedStyle: with_first_parameter

# Use && and || instead of `and` and `or`
Style/AndOr:
  Enabled: true
  EnforcedStyle: always

# Only allow comments written in ASCII
Style/AsciiComments:
  Enabled: true

# Checks for methods invoked via the :: operator
Style/ColonMethodCall:
  Enabled: true

# Use ` or %x around command literals.
Style/CommandLiteral:
  EnforcedStyle: percent_x

# TODO: Someday we should add copyrights
Style/Copyright:
  Enabled: false
  Notice: '^Copyright (\(c\) )?2[0-9]{3} .+'
  AutocorrectNotice: ''

# Avoid using double negation (!!) to convert something to a boolean value
Style/DoubleNegation:
  Enabled: true

# Replace inject with each_with_object
Style/EachWithObject:
  Enabled: true

# Avoid empty else statements.
Style/EmptyElse:
  EnforcedStyle: both

# Checks for extra/unnecessary whitespace
Style/ExtraSpacing:
  Enabled: true

# Use guard clause instead of wrapping the code inside a conditional expression
Style/GuardClause:
  Enabled: true

# Checks hash literal syntax
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
  Enabled: true
  Exclude:
    - 'config/routes.rb'

# Use `elsif` instead of `else` with only an `if` node inside
Style/IfInsideElse:
  Enabled: true

# Checks the indentation of the first element in an array
Style/IndentArray:
  Enabled: true

# Checks the indentation of the first line of the right-hand-side of a multi-line assignment.
Style/IndentAssignment:
  Enabled: true
  IndentationWidth: 2

# Checks for indentation that doesn't use two spaces.
Style/IndentationWidth:
  Enabled: true

# Use Kernel#loop for infinite loops
Style/InfiniteLoop:
  Enabled: true

# Checks for unwanted parentheses in parameterless method calls
Style/MethodCallWithoutArgsParentheses:
  Enabled: true

# Checks for parentheses around the arguments in method definitions
Style/MethodDefParentheses:
  Enabled: true

# Checks for chaining of a block after another block that spans multiple lines.
Style/MultilineBlockChain:
  Enabled: true
  Exclude:
    - 'spec/models/project_spec.rb'
    - 'spec/models/package_spec.rb'

# Checks for uses of if with a negated condition (only ifs without else)
Style/NegatedIf:
  Enabled: true

# Use ! instead not
Style/Not:
  Enabled: true

# Use 0o for octal literals
Style/NumericLiteralPrefix:
  Enabled: true

# Checks for redundant `return` expressions
Style/RedundantReturn:
  Enabled: false

# Checks for redundant uses of `self`
Style/RedundantSelf:
  Enabled: true

# This cop checks for uses of `fail` and `raise`
Style/SignalException:
  Enabled: true

# Checks for space after `!`
Style/SpaceAfterNot:
  Enabled: true

# Checks that operators have space around them.
Style/SpaceAroundOperators:
  Enabled: true

# Checks for spaces inside square brackets
Style/SpaceInsideBrackets:
  Enabled: true

# Use symbols as procs when possible
Style/SymbolProc:
  Enabled: true

# Checks for the presence of parentheses around ternary conditions
Style/TernaryParentheses:
  Enabled: true

# Checks for predicates than can be replaced by receiver.empty? and !receiver.empty?
Style/ZeroLengthPredicate:
  Enabled: true

# Checks for uses of rescue in its modifier form
Style/RescueModifier:
  Enabled: true

# Enforces the use the shorthand for self-assignment
Style/SelfAssignment:
  Enabled: true

##################### Metrics ##################################

# Checks if the length a class exceeds some maximum value
Metrics/ClassLength:
  Severity: refactor

# Checks the length of lines in the source code.
Metrics/LineLength:
  Max: 150
  IgnoredPatterns: ['^\s*#']
  Exclude:
    - 'db/**/*'

# Checks if the length a module exceeds some maximum value
Metrics/ModuleLength:
  Severity: refactor

##################### Lint ##################################

# Configuration parameters: AllowSafeAssignment. It is true by default.
Lint/AssignmentInCondition:
  Enabled: true

# Align ends correctly.
Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

# checks for private or protected access modifiers which are applied to a
# singleton method, as they do not make it private/protected.
Lint/IneffectiveAccessModifier:
  Enabled: true

# checks for literals used as the conditions or as operands in and/or expressions serving as the conditions of if/while/until.
Lint/LiteralInCondition:
  Enabled: true

# Use Kernel#loop with break rather than begin/end/until(or while)
Lint/Loop:
  Enabled: true

# Checks for nested method definitions
Lint/NestedMethodDefinition:
  Enabled: true
  Exclude:
    - 'test/functional/tag_controller_test.rb'

# checks for unused block arguments.
Lint/UnusedBlockArgument:
  Enabled: true

# Checks for access modifiers without any code
Lint/UselessAccessModifier:
  Enabled: true

# Checks for every useless assignment to local variable in every scope
Lint/UselessAssignment:
  Enabled: true

# This cop looks for error classes inheriting from `Exception`.
Lint/InheritException:
  Enabled: true

# Checks for space between a the name of a called method and a left parenthesis.
Lint/ParenthesesAsGroupedExpression:
  Enabled: true

##################### Performance ###############################

# Use yield instead of having a &block parameter and block.call
Performance/RedundantBlockCall:
  Enabled: true

# Identifies uses of `Regexp#match` and `String#match where `=~` could be used as well
Performance/RedundantMatch:
  Enabled: true

# Identifies places where Hash#merge! can be replaced by Hash#[]=
Performance/RedundantMerge:
  Enabled: true

# Identifies places where gsub can be replaced by tr or delete.
Performance/StringReplacement:
  Enabled: true

##################### Rails ##################################

Rails:
  Enabled: true

# Enforces that 'exit' calls are not used.
Rails/Exit:
  Exclude:
    - 'lib/memory_dumper.rb'

# Use `find_by` instead `where.first` and `where.take`
Rails/FindBy:
  Enabled: true

# Identify usages of http methods like `get`, `post`, `put`, `path` without the usage of keyword arguments in your tests and change them to use
# keyword arguments.
Rails/HttpPositionalArguments:
  Enabled: true

# Requires each table column to have a default value
Rails/NotNullColumn:
  Enabled: true
  Exclude:
    - 'db/migrate/20121121142111_watchlist_use_ids.rb'
    - 'db/migrate/20131020151037_make_comment_users_ids.rb'
    - 'db/migrate/20131027122410_add_primary_to_repository_architectures.rb'
    - 'db/migrate/20131209103450_add_primary_to_groups_users.rb'

# Checks for the use of output calls like puts and print
Rails/Output:
  Exclude:
    - 'app/jobs/*'
    - 'config/*'
    - 'db/**/*'
    - 'lib/**/*'
    
# Checks for the use of methods which skip validations.
Rails/SkipsModelValidations:
  Enabled: true
  Exclude:
    - 'db/migrate/*'
    - 'app/jobs/*'
    - 'spec/models/bs_request_action_spec.rb'
    - 'spec/models/review_spec.rb'

Rails/SaveBang:
  Enabled: true

# Checks for the use of old-style attribute validation macros.
Rails/Validation:
  Enabled: true

##################### Security ##################################

# checks for the use of *Kernel#eval* as it is a serious security risk.
Security/Eval:
  Enabled: true

# Checks for uses of YAML methods with potential security issues leading to remote code execution when loading from an untrusted source.
Security/YAMLLoad:
  Enabled: true

##################### Bundler ##################################

# Gems in consecutive lines should be alphabetically sorted
Bundler/OrderedGems:
  Enabled: true
