inherit_from: .rubocop_todo.yml
Rails:
  Enabled: true
AllCops:
  Exclude:
    - 'tmp/**/*'
    - 'lib/templates/**/*'
    - 'vendor/bundle/**/*'

Rails/FindBy:
  Enabled: true

# Someday we should add copyrights
Style/Copyright:
  Enabled: false
  Notice: '^Copyright (\(c\) )?2[0-9]{3} .+'
  AutocorrectNotice: ''# Configuration parameters: AllowURI, URISchemes.

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 150
  Exclude:
    - 'db/**/*'

Metrics/ClassLength:
  Severity: refactor

Metrics/ModuleLength:
  Severity: refactor

Style/CommandLiteral:
  EnforcedStyle: percent_x

Lint/EndAlignment:
  AlignWith: variable

Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
  EnforcedLastArgumentHashStyle: ignore_implicit

Style/AlignParameters:
  EnforcedStyle: with_first_parameter

# Moisés
# Configuration parameters: AllowSafeAssignment.
Lint/AssignmentInCondition:
  Enabled: true
  
Style/AndOr:
  # Whether `and` and `or` are banned only in conditionals (conditionals)
  # or completely (always).
  Enabled: true
  EnforcedStyle: always
  SupportedStyles:
    - always
    - conditionals

Style/EmptyElse:
  EnforcedStyle: both

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
  Enabled: true
  Exclude:
    - 'config/routes.rb'

Style/InfiniteLoop:
  Enabled: true
