require: rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  UseCache: true
  CacheRootDirectory: tmp/rubocop_cache_rails_dir
  MaxFilesInCache: 4000
  Exclude:
    - 'tmp/**/*'
    - 'lib/templates/**/*'
    - 'vendor/bundle/**/*'
    - 'test/fixtures/backend/**/*'
    - 'files/*'
    - 'db/data_schema.rb'

#################### Style ###########################

# We need to allow some variables related to rabbiMQ.
Style/GlobalVars:
  AllowedVariables: ['$rabbitmq_conn', '$rabbitmq_exchange', '$rabbitmq_channel']

# We disabled this cop because of Rantly.
Style/MultilineBlockChain:
  Exclude:
    - 'spec/**/*'

##################### Metrics ##################################

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'

##################### Rails ##################################

Rails:
  Enabled: true

# Actually is not possible to enable this cop because we have several overwritten methods.
Rails/DynamicFindBy:
  Enabled: false

Rails/Exit:
  Exclude:
    - 'lib/memory_dumper.rb'

RSpec/FilePath:
  Exclude:
    - 'spec/models/obs_factory/distribution_strategy_opensuse_leap15_spec.rb'

Rails/HasAndBelongsToMany:
  Enabled: false

# FIXME: Disabled due to a bug in Rubocop. Once it is fixed in this PR (https://github.com/bbatsov/rubocop/pull/5707), it could be enabled again
Rails/HttpStatus:
  Enabled: false

# Checks for the use of output calls like puts and print
Rails/Output:
  Exclude:
    - 'app/jobs/*'
    - 'config/*'
    - 'db/**/*'
    - 'lib/**/*'

# We decided not to modify old migrations
Rails/BulkChangeTable:
  Exclude:
    - 'db/migrate/20140210114542_remove_project_and_package_from_subscription.rb'
    - 'db/migrate/20140624101042_add_package_tracking.rb'
    - 'db/migrate/20140717101042_add_updateinfo_tracking.rb'
    - 'db/migrate/20140718112346_flexible_updateinfoid.rb'
    - 'db/migrate/20140721112346_delayed_job_indexes.rb'
    - 'db/migrate/20140729101042_updateinfo_tracking_second_attempt.rb'
    - 'db/migrate/20140801071042_product_version_tracking.rb'
    - 'db/migrate/20170516140442_add_several_fields_to_kiwi_repositories.rb'
    - 'db/migrate/20170607110443_add_and_remove_some_index_in_bs_request_actions.rb'
    - 'db/migrate/20170630121602_add_index_bs_requests_action.rb'
    - 'db/migrate/20170619111734_alter_notifications_to_use_polymorphic.rb'
    - 'db/migrate/20170905081525_add_has_secure_password_support.rb'
    - 'db/migrate/20170911142301_change_kiwi_package_groups_columns_from_big_int_to_int.rb'
    - 'db/migrate/20170912140257_change_kiwi_packages_columns_from_big_int_to_int.rb'
    - 'db/migrate/20171107125828_rename_kiwi_preference_types_to_kiwi_preferences.rb'
    - 'db/migrate/20180516074538_explicitly_set_charset.rb'

Style/MethodCallWithArgsParentheses:
  Enabled: true
  Exclude:
    - 'app/views/**/*'
    - 'db/migrate/**/*'
    - 'Gemfile*'
  # the cop doesn't come with a well defined list of good methods, so this
  # list is the list of offending functions when introducing. Removing functions
  # from here leads to autocorrecting calls, if you call a new DSL function, add
  # it here
  IgnoredMethods:
    - abort
    - add_column
    - add_element
    - add_foreign_key
    - add_index
    - add_reference
    - after_action
    - and_return
    - around
    - assert
    - assert_equal
    - assert_kind_of
    - assert_match
    - assert_nil
    - assert_not
    - assert_not_equal
    - assert_not_nil
    - assert_no_xml_tag
    - assert_project
    - assert_redirected_to
    - assert_response
    - assert_select
    - assert_xml_tag
    - authorize
    - belongs_to
    - call
    - change_column
    - change_column_default
    - change_column_null
    - click_button
    - click_link
    - column
    - connect
    - content
    - content_type
    - debug
    - define
    - delete
    - delete_element
    - describe
    - drop_table
    - entry
    - environment
    - error
    - exec_query
    - exit
    - expect_with
    - fatal
    - feature
    - fill_in
    - from
    - get
    - have_content
    - have_link
    - have_text
    - head
    - headers
    - hook_into
    - http_do
    - ignore_hosts
    - include
    - index
    - info
    - kill
    - load
    - localize
    - match_array
    - merge_timeout
    - message
    - mkdir
    - must_be
    - not_to
    - orm
    - parse
    - post
    - print
    - put
    - puts
    - raise
    - raise_error
    - raise_exception
    - raw_post
    - raw_put
    - read
    - redirect_back
    - redirect_to
    - references
    - register_driver
    - register_template_handler
    - remove_column
    - remove_foreign_key
    - remove_index
    - remove_reference
    - rename_column
    - rename_table
    - render
    - render_error
    - render_ok
    - require
    - require_dependency
    - required_parameters
    - require_relative
    - run
    - run_with_retry
    - set_content_type
    - shared_context
    - shared_examples
    - sprite_tag
    - start
    - stopped
    - strftime
    - task
    - test_framework
    - throw
    - to
    - validate
    - validate_presence_of
    - validate_type
    - value
    - visit
    - warn
    - write
    - yield
    - ymp
