# Edit this Gemfile to bundle your application's dependencies.
# This preamble is the current preamble for Rails 3 apps; edit as needed.
source 'https://rubygems.org'

gem 'rails-api'
gem 'activerecord', '~> 4.0'
gem 'actionmailer'

gem 'mysql2'

# activexml require
gem 'nokogiri', '~>1.6.0'

# make sure we can delay tasks
gem 'delayed_job_active_record', '>= 4.0.0'
# to have the delayed job daemon
gem 'daemons'

# to fill errbit
gem 'hoptoad_notifier', "~> 2.3"

gem 'rdoc'
gem 'xmlhash', '>=1.3.6'
gem 'ruby-ldap', require: false

# memcache client
gem 'dalli', require: false

# JSON library - the default json conflicts with activerecord (by means of vice-versa monkey patching)
gem 'yajl-ruby'

# for searching in webui
gem 'thinking-sphinx'

# don't rely on cron+rake 
gem 'clockwork'

group :production do
  # if you have an account, it can be configured by
  # placing a config/newrelic.yml
  gem 'newrelic_rpm'
end

group :test do
  gem 'database_cleaner', '>= 1.0.1'
  gem 'ci_reporter'
  gem 'simplecov-rcov', :require => false
  gem 'minitest', '< 5.0'
  # colorize minitest output
  gem 'minitest-colorize'
  # generate random long strings
  gem 'faker'
  # freeze time
  gem 'timecop'
  # to fake backend replies
  gem 'webmock', '>= 1.9.0'
  # for code quality checks
  gem 'flog', '> 4.1.0'
end

group :development do
  gem 'pry', '>= 0.9.12'
end
