# Edit this Gemfile to bundle your application's dependencies.
# This preamble is the current preamble for Rails 3 apps; edit as needed.
source 'https://rubygems.org'

gem 'rails-api'
gem 'activerecord', '~> 4.0'
gem 'actionmailer'

gem 'mysql2'
gem 'daemons'
gem 'nokogiri', '~>1.6.0'
gem 'delayed_job', '~> 4.0.0.beta1'
gem 'delayed_job_active_record', '~> 4.0.0.beta2'
gem 'hoptoad_notifier', "~> 2.3"
gem 'rdoc'
gem 'xmlhash', '>=1.3.5'
gem 'ruby-ldap', :require => false
gem 'dalli', :require => false
gem 'yajl-ruby'

# don't rely on cron+rake 
gem 'clockwork'

group :production do
  # if you have an account, it can be configured by
  # placing a config/newrelic.yml
  gem 'newrelic_rpm'
end

group :test do
  gem 'database_cleaner', '>= 1.0.1'
  gem 'ci_reporter'
  gem 'simplecov-rcov', :require => false
  gem 'minitest', '< 5.0'
  gem 'minitest-colorize'
  gem 'faker'
  gem 'timecop'
  gem 'webmock', '>= 1.9.0'
end

group :development do
  gem 'pry', '>= 0.9.12'
end
