web: bundle exec rails server -b 0.0.0.0
delayed: bundle exec script/delayed_job.api.rb run
clock: bundle exec clockworkd --log-dir=log -l -c config/clock.rb run
search: (sleep 60 && bundle exec rake ts:rt:index) & bundle exec rake ts:rebuild NODETACH=true && fg
mailcatcher: mailcatcher --ip 0.0.0.0 -f --no-quit -v
