web: bundle exec rails server
delayed: bundle exec script/delayed_job.api.rb run
clock: bundle exec clockworkd --log-dir=log -l -c config/clock.rb run 
search: bundle exec rake ts:rebuild NODETACH=true
mailcatcher: mailcatcher --ip 0.0.0.0 -f --no-quit -v
