web: (bundle check || bundle install) && bundle exec rails server -b 0.0.0.0
delayed: (bundle check || bundle install) && bundle exec script/delayed_job.api.rb run
clock: (bundle check || bundle install) && bundle exec clockworkd --log-dir=log -l -c config/clock.rb run
search: (bundle check || bundle install) && bundle exec rake ts:rebuild NODETACH=true
mailcatcher: mailcatcher --ip 0.0.0.0 -f --no-quit -v
