#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/boot'
require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))

packs = DbPackage.find :all, :conditions => "develpackage_id is not null"

packs.each do |p|
  begin
    p.resolve_devel_package
  rescue DbPackage::CycleError => e
    puts e.message
  end
end
