#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/boot'
require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))

proj = ARGV[0]
if ! proj
   puts "usage: update_project <project>"
   exit 1
end 
dbproj = DbProject.find_by_name(proj)
if ! dbproj
  puts "invalid project " + proj
  exit 1
end
backend = ActiveXML::Config.transport_for :packstatus
mypackages = dbproj.complex_status(backend)
key='project_status_%s' % dbproj.name
Rails.cache.write(key, mypackages)

