# This file is automatically generated by 'rake anitya:update_distros'
# Last updated: 2026-02-20 14:14:36 UTC
ANITYA_DISTROS = [
  '(Beyond) Linux From Scratch', 'ALT', 'AOSC OS', 'Adélie Linux', 'AerynOS', 'AlmaLinux', 'Alpine', 'Amazon Linux',
  'Arch Linux', 'Arch Linux AUR', 'Arch Linux RISC-V', 'Bootstrapper', 'Buildroot', 'COPR', 'CPE NVD NIST', 'CRUX',
  'CentOS', 'Centos', 'Chimera Linux', 'Chromebrew', 'Clear Linux', 'Cokybit ', 'Conda', 'Cygwin',
  'Debian', 'Devuan', 'Docker', 'DragonFly BSD', 'Endless OS', 'F-Droid', 'FZUG', 'Fedora',
  'Fedora EPEL', 'Flathub', 'FreeBSD', 'FreeBSD (FreshPorts)', 'Freedesktop SDK', 'FreshPorts', 'Gentoo', 'Guix',
  'Haiku', 'Homebrew', 'Homebrew Cask', 'IPFire', 'IUS', 'KaOS', 'Kylin-Linux-Advanced-Serve', 'LibreELEC',
  'MacOS', 'MacPorts', 'Mageia', 'Manjaro Linux', 'Meson WrapDB', 'NetBSD', 'NethServer', 'NixOS',
  'Nobara', 'OSX', 'OpenBSD', 'OpenEmbedded', 'OpenMandriva', 'OpenMesh', 'OpenProject', 'OpenWrt',
  'PLD-Linux', 'Parrot OS', 'Parrot OS ', 'Pentoo', 'RHEL', 'RPM Fusion', 'RPM Sphere', 'Raspbian',
  'RedHat', 'Rocky Linux', 'RussianFedora', 'Selinux', 'SlackBuilds', 'Solaris', 'Solus', 'Spack',
  'Sudachi emulator', 'Timesys', 'Tiny Core Linux', 'Ubuntu', 'Ultramarine Linux', 'UnitedRPMs', 'Vanilla OS', 'Void',
  'Windows', 'Wolfi', 'alpine', 'anolis', 'cheese', 'deepin', 'foobar', 'hackpost',
  'itachi_re', 'jultager', 'libreoffice', 'oVirt', 'obs.infoserver.lv', 'openEuler', 'openKylin', 'openSUSE',
  'openSUSE Leap', 'openSUSE Slowroll', 'openSUSE Tumbleweed', 'openSUSE:GNOME:Next', 'pkgsrc', 'poky', 'postmarketOS', 'ruby-ox',
  'stagex', 'test', 'test2', 'yiffOS'
].freeze
