# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/actionview/all/actionview.rbi
#
# actionview-5.2.3
module ActionView
  def self.eager_load!; end
  def self.gem_version; end
  def self.version; end
  extend ActiveSupport::Autoload
end
module ActionView::VERSION
end
class ActionView::Railtie < Rails::Engine
end
module ActionView::Helpers
  def self.eager_load!; end
  extend ActiveSupport::Autoload
  extend ActiveSupport::Concern
  include ActionView::Helpers::ActiveModelHelper
  include ActionView::Helpers::AssetTagHelper
  include ActionView::Helpers::AssetUrlHelper
  include ActionView::Helpers::AtomFeedHelper
  include ActionView::Helpers::CacheHelper
  include ActionView::Helpers::CaptureHelper
  include ActionView::Helpers::ControllerHelper
  include ActionView::Helpers::CspHelper
  include ActionView::Helpers::CsrfHelper
  include ActionView::Helpers::DateHelper
  include ActionView::Helpers::DebugHelper
  include ActionView::Helpers::FormHelper
  include ActionView::Helpers::FormOptionsHelper
  include ActionView::Helpers::FormTagHelper
  include ActionView::Helpers::JavaScriptHelper
  include ActionView::Helpers::NumberHelper
  include ActionView::Helpers::OutputSafetyHelper
  include ActionView::Helpers::RecordTagHelper
  include ActionView::Helpers::RenderingHelper
  include ActionView::Helpers::SanitizeHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::TranslationHelper
  include ActionView::Helpers::UrlHelper
  include ActiveSupport::Benchmarkable
end
module ActionView::Helpers::ActiveModelHelper
end
module ActionView::Helpers::ActiveModelInstanceTag
  def content_tag(type, options, *arg2); end
  def error_message; end
  def error_wrapping(html_tag); end
  def object; end
  def object_has_errors?; end
  def select_markup_helper?(type); end
  def tag(type, options, *arg2); end
  def tag_generate_errors?(options); end
end
module ActionView::Helpers::AssetUrlHelper
  def asset_path(source, options = nil); end
  def asset_url(source, options = nil); end
  def audio_path(source, options = nil); end
  def audio_url(source, options = nil); end
  def compute_asset_extname(source, options = nil); end
  def compute_asset_host(source = nil, options = nil); end
  def compute_asset_path(source, options = nil); end
  def font_path(source, options = nil); end
  def font_url(source, options = nil); end
  def image_path(source, options = nil); end
  def image_url(source, options = nil); end
  def javascript_path(source, options = nil); end
  def javascript_url(source, options = nil); end
  def path_to_asset(source, options = nil); end
  def path_to_audio(source, options = nil); end
  def path_to_font(source, options = nil); end
  def path_to_image(source, options = nil); end
  def path_to_javascript(source, options = nil); end
  def path_to_stylesheet(source, options = nil); end
  def path_to_video(source, options = nil); end
  def public_compute_asset_path(source, options = nil); end
  def stylesheet_path(source, options = nil); end
  def stylesheet_url(source, options = nil); end
  def url_to_asset(source, options = nil); end
  def url_to_audio(source, options = nil); end
  def url_to_font(source, options = nil); end
  def url_to_image(source, options = nil); end
  def url_to_javascript(source, options = nil); end
  def url_to_stylesheet(source, options = nil); end
  def url_to_video(source, options = nil); end
  def video_path(source, options = nil); end
  def video_url(source, options = nil); end
end
module ActionView::Helpers::CaptureHelper
  def capture(*args, &block); end
  def content_for(name, content = nil, options = nil, &block); end
  def content_for?(name); end
  def provide(name, content = nil, &block); end
  def with_output_buffer(*args, &block); end
end
module ActionView::Helpers::OutputSafetyHelper
  def raw(stringish); end
  def safe_join(array, sep = nil); end
  def to_sentence(array, options = nil); end
end
module ActionView::Helpers::TagHelper
  def cdata_section(content); end
  def content_tag(name, *args, &block); end
  def escape_once(html); end
  def tag(name = nil, options = nil, open = nil, escape = nil); end
  def tag_builder; end
  extend ActiveSupport::Concern
  include ActionView::Helpers::CaptureHelper
  include ActionView::Helpers::OutputSafetyHelper
end
class ActionView::Helpers::TagHelper::TagBuilder
  def boolean_tag_option(key); end
  def content_tag_string(name, content, options, escape = nil); end
  def initialize(view_context); end
  def method_missing(called, *args, &block); end
  def prefix_tag_option(prefix, key, value, escape); end
  def respond_to_missing?(*args); end
  def tag_option(key, value, escape); end
  def tag_options(options, escape = nil); end
  def tag_string(name, content = nil, escape_attributes: nil, **options, &block); end
  include ActionView::Helpers::CaptureHelper
  include ActionView::Helpers::OutputSafetyHelper
end
module ActionView::Helpers::AssetTagHelper
  def audio_tag(*sources); end
  def auto_discovery_link_tag(type = nil, url_options = nil, tag_options = nil); end
  def check_for_image_tag_errors(options); end
  def extract_dimensions(size); end
  def favicon_link_tag(source = nil, options = nil); end
  def image_alt(src); end
  def image_tag(source, options = nil); end
  def javascript_include_tag(*sources); end
  def multiple_sources_tag_builder(type, sources); end
  def preload_link_tag(source, options = nil); end
  def resolve_image_source(source, skip_pipeline); end
  def resolve_link_as(extname, mime_type); end
  def stylesheet_link_tag(*sources); end
  def video_tag(*sources); end
  extend ActiveSupport::Concern
  include ActionView::Helpers::AssetUrlHelper
  include ActionView::Helpers::TagHelper
end
module ActionView::Helpers::AtomFeedHelper
  def atom_feed(options = nil, &block); end
end
class ActionView::Helpers::AtomFeedHelper::AtomBuilder
  def initialize(xml); end
  def method_missing(method, *arguments, &block); end
  def xhtml_block?(method, arguments); end
end
class ActionView::Helpers::AtomFeedHelper::AtomFeedBuilder < ActionView::Helpers::AtomFeedHelper::AtomBuilder
  def entry(record, options = nil); end
  def initialize(xml, view, feed_options = nil); end
  def updated(date_or_time = nil); end
end
module ActionView::Helpers::CacheHelper
  def cache(name = nil, options = nil, &block); end
  def cache_fragment_name(name = nil, skip_digest: nil, virtual_path: nil); end
  def cache_if(condition, name = nil, options = nil, &block); end
  def cache_unless(condition, name = nil, options = nil, &block); end
  def fragment_for(name = nil, options = nil, &block); end
  def fragment_name_with_digest(name, virtual_path); end
  def read_fragment_for(name, options); end
  def write_fragment_for(name, options); end
end
module ActionView::Helpers::ControllerHelper
  def action_name(*args, &block); end
  def assign_controller(controller); end
  def controller; end
  def controller=(arg0); end
  def controller_name(*args, &block); end
  def controller_path(*args, &block); end
  def cookies(*args, &block); end
  def flash(*args, &block); end
  def headers(*args, &block); end
  def logger; end
  def params(*args, &block); end
  def request; end
  def request=(arg0); end
  def request_forgery_protection_token(*args, &block); end
  def respond_to?(method_name, include_private = nil); end
  def response(*args, &block); end
  def session(*args, &block); end
end
module ActionView::Helpers::CspHelper
  def csp_meta_tag; end
end
module ActionView::Helpers::CsrfHelper
  def csrf_meta_tag; end
  def csrf_meta_tags; end
end
module ActionView::Helpers::DateHelper
  def date_select(object_name, method, options = nil, html_options = nil); end
  def datetime_select(object_name, method, options = nil, html_options = nil); end
  def distance_of_time_in_words(from_time, to_time = nil, options = nil); end
  def distance_of_time_in_words_to_now(from_time, options = nil); end
  def normalize_distance_of_time_argument_to_time(value); end
  def select_date(date = nil, options = nil, html_options = nil); end
  def select_datetime(datetime = nil, options = nil, html_options = nil); end
  def select_day(date, options = nil, html_options = nil); end
  def select_hour(datetime, options = nil, html_options = nil); end
  def select_minute(datetime, options = nil, html_options = nil); end
  def select_month(date, options = nil, html_options = nil); end
  def select_second(datetime, options = nil, html_options = nil); end
  def select_time(datetime = nil, options = nil, html_options = nil); end
  def select_year(date, options = nil, html_options = nil); end
  def time_ago_in_words(from_time, options = nil); end
  def time_select(object_name, method, options = nil, html_options = nil); end
  def time_tag(date_or_time, *args, &block); end
end
class ActionView::Helpers::DateTimeSelector
  def build_hidden(type, value); end
  def build_options(selected, options = nil); end
  def build_options_and_select(type, selected, options = nil); end
  def build_select(type, select_options_as_html); end
  def build_selects_from_types(order); end
  def css_class_attribute(type, html_options_class, options); end
  def date_order; end
  def day; end
  def hour; end
  def initialize(datetime, options = nil, html_options = nil); end
  def input_id_from_type(type); end
  def input_name_from_type(type); end
  def min; end
  def month; end
  def month_name(number); end
  def month_names; end
  def prompt_option_tag(type, options); end
  def sec; end
  def select_date; end
  def select_datetime; end
  def select_day; end
  def select_hour; end
  def select_minute; end
  def select_month; end
  def select_second; end
  def select_time; end
  def select_year; end
  def separator(type); end
  def set_day_if_discarded; end
  def translated_date_order; end
  def translated_month_names; end
  def year; end
  include ActionView::Helpers::TagHelper
end
class ActionView::Helpers::FormBuilder
  def button(value = nil, options = nil, &block); end
  def check_box(method, options = nil, checked_value = nil, unchecked_value = nil); end
  def collection_check_boxes(method, collection, value_method, text_method, options = nil, html_options = nil, &block); end
  def collection_radio_buttons(method, collection, value_method, text_method, options = nil, html_options = nil, &block); end
  def collection_select(method, collection, value_method, text_method, options = nil, html_options = nil); end
  def color_field(method, options = nil); end
  def convert_to_legacy_options(options); end
  def date_field(method, options = nil); end
  def date_select(method, options = nil, html_options = nil); end
  def datetime_field(method, options = nil); end
  def datetime_local_field(method, options = nil); end
  def datetime_select(method, options = nil, html_options = nil); end
  def email_field(method, options = nil); end
  def emitted_hidden_id?; end
  def field_helpers; end
  def field_helpers=(val); end
  def field_helpers?; end
  def fields(scope = nil, model: nil, **options, &block); end
  def fields_for(record_name, record_object = nil, fields_options = nil, &block); end
  def fields_for_nested_model(name, object, fields_options, block); end
  def fields_for_with_nested_attributes(association_name, association, options, block); end
  def file_field(method, options = nil); end
  def grouped_collection_select(method, collection, group_method, group_label_method, option_key_method, option_value_method, options = nil, html_options = nil); end
  def hidden_field(method, options = nil); end
  def index; end
  def initialize(object_name, object, template, options); end
  def label(method, text = nil, options = nil, &block); end
  def month_field(method, options = nil); end
  def multipart; end
  def multipart=(multipart); end
  def multipart?; end
  def nested_attributes_association?(association_name); end
  def nested_child_index(name); end
  def number_field(method, options = nil); end
  def object; end
  def object=(arg0); end
  def object_name; end
  def object_name=(arg0); end
  def objectify_options(options); end
  def options; end
  def options=(arg0); end
  def password_field(method, options = nil); end
  def phone_field(method, options = nil); end
  def radio_button(method, tag_value, options = nil); end
  def range_field(method, options = nil); end
  def search_field(method, options = nil); end
  def select(method, choices = nil, options = nil, html_options = nil, &block); end
  def self._to_partial_path; end
  def self.field_helpers; end
  def self.field_helpers=(val); end
  def self.field_helpers?; end
  def submit(value = nil, options = nil); end
  def submit_default_value; end
  def telephone_field(method, options = nil); end
  def text_area(method, options = nil); end
  def text_field(method, options = nil); end
  def time_field(method, options = nil); end
  def time_select(method, options = nil, html_options = nil); end
  def time_zone_select(method, priority_zones = nil, options = nil, html_options = nil); end
  def to_model; end
  def to_partial_path; end
  def url_field(method, options = nil); end
  def week_field(method, options = nil); end
  include ActionView::ModelNaming
end
module ActionView::Helpers::DebugHelper
  def debug(object); end
  include ActionView::Helpers::TagHelper
end
module ActionView::Helpers::JavaScriptHelper
  def escape_javascript(javascript); end
  def j(javascript); end
  def javascript_cdata_section(content); end
  def javascript_tag(content_or_options_with_block = nil, html_options = nil, &block); end
end
module ActionView::Helpers::UrlHelper
  def _back_url; end
  def _filtered_referrer; end
  def add_method_to_attributes!(html_options, method); end
  def button_to(name = nil, options = nil, html_options = nil, &block); end
  def convert_options_to_data_attributes(options, html_options); end
  def current_page?(options, check_parameters: nil); end
  def link_to(name = nil, options = nil, html_options = nil, &block); end
  def link_to_if(condition, name, options = nil, html_options = nil, &block); end
  def link_to_remote_options?(options); end
  def link_to_unless(condition, name, options = nil, html_options = nil, &block); end
  def link_to_unless_current(name, options = nil, html_options = nil, &block); end
  def mail_to(email_address, name = nil, html_options = nil, &block); end
  def method_not_get_method?(method); end
  def method_tag(method); end
  def to_form_params(attribute, namespace = nil); end
  def token_tag(token = nil, form_options: nil); end
  def url_for(options = nil); end
  extend ActiveSupport::Concern
  include ActionView::Helpers::TagHelper
end
module ActionView::Helpers::UrlHelper::ClassMethods
  def _url_for_modules; end
end
module ActionView::Helpers::SanitizeHelper
  def sanitize(html, options = nil); end
  def sanitize_css(style); end
  def strip_links(html); end
  def strip_tags(html); end
  extend ActiveSupport::Concern
end
module ActionView::Helpers::SanitizeHelper::ClassMethods
  def full_sanitizer; end
  def full_sanitizer=(arg0); end
  def link_sanitizer; end
  def link_sanitizer=(arg0); end
  def sanitized_allowed_attributes; end
  def sanitized_allowed_tags; end
  def sanitizer_vendor; end
  def white_list_sanitizer; end
  def white_list_sanitizer=(arg0); end
end
module ActionView::Helpers::TextHelper
  def concat(string); end
  def current_cycle(name = nil); end
  def cut_excerpt_part(part_position, part, separator, options); end
  def cycle(first_value, *values); end
  def excerpt(text, phrase, options = nil); end
  def get_cycle(name); end
  def highlight(text, phrases, options = nil); end
  def pluralize(count, singular, plural_arg = nil, plural: nil, locale: nil); end
  def reset_cycle(name = nil); end
  def safe_concat(string); end
  def set_cycle(name, cycle_object); end
  def simple_format(text, html_options = nil, options = nil); end
  def split_paragraphs(text); end
  def truncate(text, options = nil, &block); end
  def word_wrap(text, line_width: nil, break_sequence: nil); end
  extend ActiveSupport::Concern
  include ActionView::Helpers::OutputSafetyHelper
  include ActionView::Helpers::SanitizeHelper
  include ActionView::Helpers::TagHelper
end
class ActionView::Helpers::TextHelper::Cycle
  def current_value; end
  def initialize(first_value, *values); end
  def next_index; end
  def previous_index; end
  def reset; end
  def step_index(n); end
  def to_s; end
  def values; end
end
module ActionView::Helpers::FormTagHelper
  def button_tag(content_or_options = nil, options = nil, &block); end
  def check_box_tag(name, value = nil, checked = nil, options = nil); end
  def color_field_tag(name, value = nil, options = nil); end
  def convert_direct_upload_option_to_url(options); end
  def date_field_tag(name, value = nil, options = nil); end
  def datetime_field_tag(name, value = nil, options = nil); end
  def datetime_local_field_tag(name, value = nil, options = nil); end
  def email_field_tag(name, value = nil, options = nil); end
  def embed_authenticity_token_in_remote_forms; end
  def embed_authenticity_token_in_remote_forms=(obj); end
  def extra_tags_for_form(html_options); end
  def field_set_tag(legend = nil, options = nil, &block); end
  def file_field_tag(name, options = nil); end
  def form_tag(*args, &block); end
  def form_tag_html(html_options); end
  def form_tag_with_body(html_options, content); end
  def hidden_field_tag(name, value = nil, options = nil); end
  def html_options_for_form(url_for_options, options); end
  def image_submit_tag(source, options = nil); end
  def label_tag(name = nil, content_or_options = nil, options = nil, &block); end
  def month_field_tag(name, value = nil, options = nil); end
  def number_field_tag(name, value = nil, options = nil); end
  def password_field_tag(name = nil, value = nil, options = nil); end
  def phone_field_tag(name, value = nil, options = nil); end
  def radio_button_tag(name, value, checked = nil, options = nil); end
  def range_field_tag(name, value = nil, options = nil); end
  def sanitize_to_id(name); end
  def search_field_tag(name, value = nil, options = nil); end
  def select_tag(name, option_tags = nil, options = nil); end
  def self.embed_authenticity_token_in_remote_forms; end
  def self.embed_authenticity_token_in_remote_forms=(obj); end
  def set_default_disable_with(value, tag_options); end
  def submit_tag(value = nil, options = nil); end
  def telephone_field_tag(name, value = nil, options = nil); end
  def text_area_tag(name, content = nil, options = nil); end
  def text_field_tag(name, value = nil, options = nil); end
  def time_field_tag(name, value = nil, options = nil); end
  def url_field_tag(name, value = nil, options = nil); end
  def utf8_enforcer_tag; end
  def week_field_tag(name, value = nil, options = nil); end
  extend ActiveSupport::Concern
  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::UrlHelper
end
module ActionView::ModelNaming
  def convert_to_model(object); end
  def model_name_from_record_or_class(record_or_class); end
end
module ActionView::RecordIdentifier
  def dom_class(record_or_class, prefix = nil); end
  def dom_id(record, prefix = nil); end
  def record_key_for_dom_id(record); end
  extend ActionView::ModelNaming
  extend ActionView::RecordIdentifier
  include ActionView::ModelNaming
end
module ActionView::Helpers::FormHelper
  def apply_form_for_options!(record, object, options); end
  def check_box(object_name, method, options = nil, checked_value = nil, unchecked_value = nil); end
  def color_field(object_name, method, options = nil); end
  def date_field(object_name, method, options = nil); end
  def datetime_field(object_name, method, options = nil); end
  def datetime_local_field(object_name, method, options = nil); end
  def default_form_builder; end
  def default_form_builder=(arg0); end
  def default_form_builder_class; end
  def email_field(object_name, method, options = nil); end
  def fields(scope = nil, model: nil, **options, &block); end
  def fields_for(record_name, record_object = nil, options = nil, &block); end
  def file_field(object_name, method, options = nil); end
  def form_for(*args, &block); end
  def form_with(model: nil, scope: nil, url: nil, format: nil, **options); end
  def form_with_generates_ids; end
  def form_with_generates_ids=(obj); end
  def form_with_generates_remote_forms; end
  def form_with_generates_remote_forms=(obj); end
  def hidden_field(object_name, method, options = nil); end
  def html_options_for_form_with(url_for_options = nil, model = nil, html: nil, local: nil, skip_enforcing_utf8: nil, **options); end
  def instantiate_builder(record_name, record_object, options); end
  def label(object_name, method, content_or_options = nil, options = nil, &block); end
  def month_field(object_name, method, options = nil); end
  def number_field(object_name, method, options = nil); end
  def password_field(object_name, method, options = nil); end
  def phone_field(object_name, method, options = nil); end
  def radio_button(object_name, method, tag_value, options = nil); end
  def range_field(object_name, method, options = nil); end
  def search_field(object_name, method, options = nil); end
  def self.form_with_generates_ids; end
  def self.form_with_generates_ids=(obj); end
  def self.form_with_generates_remote_forms; end
  def self.form_with_generates_remote_forms=(obj); end
  def telephone_field(object_name, method, options = nil); end
  def text_area(object_name, method, options = nil); end
  def text_field(object_name, method, options = nil); end
  def time_field(object_name, method, options = nil); end
  def url_field(object_name, method, options = nil); end
  def week_field(object_name, method, options = nil); end
  extend ActiveSupport::Concern
  include ActionView::Helpers::FormTagHelper
  include ActionView::Helpers::UrlHelper
  include ActionView::ModelNaming
  include ActionView::RecordIdentifier
end
module ActionView::Helpers::FormOptionsHelper
  def collection_check_boxes(object, method, collection, value_method, text_method, options = nil, html_options = nil, &block); end
  def collection_radio_buttons(object, method, collection, value_method, text_method, options = nil, html_options = nil, &block); end
  def collection_select(object, method, collection, value_method, text_method, options = nil, html_options = nil); end
  def extract_selected_and_disabled(selected); end
  def extract_values_from_collection(collection, value_method, selected); end
  def grouped_collection_select(object, method, collection, group_method, group_label_method, option_key_method, option_value_method, options = nil, html_options = nil); end
  def grouped_options_for_select(grouped_options, selected_key = nil, options = nil); end
  def option_groups_from_collection_for_select(collection, group_method, group_label_method, option_key_method, option_value_method, selected_key = nil); end
  def option_html_attributes(element); end
  def option_text_and_value(option); end
  def option_value_selected?(value, selected); end
  def options_for_select(container, selected = nil); end
  def options_from_collection_for_select(collection, value_method, text_method, selected = nil); end
  def prompt_text(prompt); end
  def select(object, method, choices = nil, options = nil, html_options = nil, &block); end
  def time_zone_options_for_select(selected = nil, priority_zones = nil, model = nil); end
  def time_zone_select(object, method, priority_zones = nil, options = nil, html_options = nil); end
  def value_for_collection(item, value); end
  extend ActionView::Helpers::SanitizeHelper::ClassMethods
  include ActionView::Helpers::SanitizeHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TextHelper
end
module ActionView::Helpers::NumberHelper
  def delegate_number_helper_method(method, number, options); end
  def escape_units(units); end
  def escape_unsafe_options(options); end
  def number_to_currency(number, options = nil); end
  def number_to_human(number, options = nil); end
  def number_to_human_size(number, options = nil); end
  def number_to_percentage(number, options = nil); end
  def number_to_phone(number, options = nil); end
  def number_with_delimiter(number, options = nil); end
  def number_with_precision(number, options = nil); end
  def parse_float(number, raise_error); end
  def valid_float?(number); end
  def wrap_with_output_safety_handling(number, raise_on_invalid, &block); end
end
class ActionView::Helpers::NumberHelper::InvalidNumberError < StandardError
  def initialize(number); end
  def number; end
  def number=(arg0); end
end
module ActionView::Helpers::RecordTagHelper
  def content_tag_for(*arg0); end
  def div_for(*arg0); end
end
module ActionView::Helpers::RenderingHelper
  def _layout_for(*args, &block); end
  def render(options = nil, locals = nil, &block); end
end
module ActionView::Helpers::TranslationHelper
  def html_safe_translation_key?(key); end
  def l(*args); end
  def localize(*args); end
  def scope_key_by_partial(key); end
  def t(key, options = nil); end
  def translate(key, options = nil); end
  extend ActiveSupport::Concern
  include ActionView::Helpers::TagHelper
end
class ActionView::LogSubscriber < ActiveSupport::LogSubscriber
end
module ActionView::CompiledTemplates
end
module ActionView::Context
  def _layout_for(name = nil); end
  def _prepare_context; end
  def output_buffer; end
  def output_buffer=(arg0); end
  def view_flow; end
  def view_flow=(arg0); end
  include ActionView::CompiledTemplates
end
class ActionView::Template
  def compile!(view); end
  def compile(mod); end
  def encode!; end
  def formats; end
  def formats=(arg0); end
  def handle_render_error(view, e); end
  def handler; end
  def identifier; end
  def identifier_method_name; end
  def initialize(source, identifier, handler, details); end
  def inspect; end
  def instrument(action, &block); end
  def instrument_payload; end
  def instrument_render_template(&block); end
  def locals; end
  def locals=(arg0); end
  def locals_code; end
  def method_name; end
  def original_encoding; end
  def refresh(view); end
  def render(view, locals, buffer = nil, &block); end
  def source; end
  def supports_streaming?; end
  def type; end
  def updated_at; end
  def variants; end
  def variants=(arg0); end
  def virtual_path; end
  def virtual_path=(arg0); end
  extend ActionView::Template::Handlers
  extend ActiveSupport::Autoload
end
module ActionView::Template::Handlers
  def handler_for_extension(extension); end
  def register_default_template_handler(extension, klass); end
  def register_template_handler(*extensions, handler); end
  def registered_template_handler(extension); end
  def self.extended(base); end
  def self.extensions; end
  def template_handler_extensions; end
  def unregister_template_handler(*extensions); end
end
class ActionView::Template::Handlers::Raw
  def call(template); end
end
class ActionView::Template::Handlers::ERB
  def call(template); end
  def erb_implementation; end
  def erb_implementation=(val); end
  def erb_implementation?; end
  def erb_trim_mode; end
  def erb_trim_mode=(val); end
  def erb_trim_mode?; end
  def escape_whitelist; end
  def escape_whitelist=(val); end
  def escape_whitelist?; end
  def handles_encoding?; end
  def self.call(template); end
  def self.erb_implementation; end
  def self.erb_implementation=(val); end
  def self.erb_implementation?; end
  def self.erb_trim_mode; end
  def self.erb_trim_mode=(val); end
  def self.erb_trim_mode?; end
  def self.escape_whitelist; end
  def self.escape_whitelist=(val); end
  def self.escape_whitelist?; end
  def supports_streaming?; end
  def valid_encoding(string, encoding); end
end
class ActionView::Template::Handlers::ERB::Erubi < Erubi::Engine
  def add_code(code); end
  def add_expression(indicator, code); end
  def add_postamble(_); end
  def add_text(text); end
  def evaluate(action_view_erb_handler_context); end
  def flush_newline_if_pending(src); end
  def initialize(input, properties = nil); end
end
class ActionView::Template::Handlers::Html < ActionView::Template::Handlers::Raw
  def call(template); end
end
class ActionView::Template::Handlers::Builder
  def call(template); end
  def default_format; end
  def default_format=(val); end
  def default_format?; end
  def require_engine; end
  def self.default_format; end
  def self.default_format=(val); end
  def self.default_format?; end
end
class ActionView::Resolver
  def build_path(name, prefix, partial); end
  def cached(key, path_info, details, locals); end
  def caching; end
  def caching=(obj); end
  def caching?(*args, &block); end
  def clear_cache; end
  def decorate(templates, path_info, details, locals); end
  def find_all(name, prefix = nil, partial = nil, details = nil, key = nil, locals = nil); end
  def find_all_anywhere(name, prefix, partial = nil, details = nil, key = nil, locals = nil); end
  def find_all_with_query(query); end
  def find_templates(name, prefix, partial, details, outside_app_allowed = nil); end
  def initialize; end
  def self.caching; end
  def self.caching=(obj); end
  def self.caching?; end
end
class ActionView::Resolver::Path
  def initialize(name, prefix, partial, virtual); end
  def name; end
  def partial; end
  def partial?; end
  def prefix; end
  def self.build(name, prefix, partial); end
  def to_s; end
  def to_str; end
  def virtual; end
end
class ActionView::Resolver::Cache
  def cache(key, name, prefix, partial, locals); end
  def cache_query(query); end
  def canonical_no_templates(templates); end
  def clear; end
  def initialize; end
  def inspect; end
  def size; end
  def templates_have_changed?(cached_templates, fresh_templates); end
end
class ActionView::Resolver::Cache::SmallCache < Concurrent::Map
  def initialize(options = nil); end
end
class ActionView::PathResolver < ActionView::Resolver
  def build_query(path, details); end
  def escape_entry(entry); end
  def extract_handler_and_format_and_variant(path); end
  def find_template_paths(query); end
  def find_templates(name, prefix, partial, details, outside_app_allowed = nil); end
  def initialize(pattern = nil); end
  def inside_path?(path, filename); end
  def mtime(p); end
  def query(path, details, formats, outside_app_allowed); end
  def reject_files_external_to_app(files); end
end
class ActionView::FileSystemResolver < ActionView::PathResolver
  def ==(resolver); end
  def eql?(resolver); end
  def initialize(path, pattern = nil); end
  def to_path; end
  def to_s; end
end
class ActionView::OptimizedFileSystemResolver < ActionView::FileSystemResolver
  def build_query(path, details); end
end
class ActionView::FallbackFileSystemResolver < ActionView::FileSystemResolver
  def decorate(*arg0); end
  def self.instances; end
end
class ActionView::LookupContext
  def digest_cache; end
  def fallbacks; end
  def fallbacks=(obj); end
  def formats=(values); end
  def initialize(view_paths, details = nil, prefixes = nil); end
  def initialize_details(target, details); end
  def locale; end
  def locale=(value); end
  def prefixes; end
  def prefixes=(arg0); end
  def registered_details; end
  def registered_details=(obj); end
  def rendered_format; end
  def rendered_format=(arg0); end
  def self.fallbacks; end
  def self.fallbacks=(obj); end
  def self.register_detail(name, &block); end
  def self.registered_details; end
  def self.registered_details=(obj); end
  include ActionView::LookupContext::Accessors
  include ActionView::LookupContext::DetailsCache
  include ActionView::LookupContext::ViewPaths
end
module ActionView::LookupContext::Accessors
  def default_formats; end
  def default_handlers; end
  def default_locale; end
  def default_variants; end
  def formats; end
  def formats=(value); end
  def handlers; end
  def handlers=(value); end
  def locale; end
  def locale=(value); end
  def variants; end
  def variants=(value); end
end
class ActionView::LookupContext::DetailsKey
  def eql?(arg0); end
  def self.clear; end
  def self.digest_caches; end
  def self.get(details); end
end
module ActionView::LookupContext::DetailsCache
  def _set_detail(key, value); end
  def cache; end
  def cache=(arg0); end
  def details_key; end
  def disable_cache; end
end
module ActionView::LookupContext::ViewPaths
  def any?(name, prefixes = nil, partial = nil); end
  def any_templates?(name, prefixes = nil, partial = nil); end
  def args_for_any(name, prefixes, partial); end
  def args_for_lookup(name, prefixes, partial, keys, details_options); end
  def detail_args_for(options); end
  def detail_args_for_any; end
  def exists?(name, prefixes = nil, partial = nil, keys = nil, **options); end
  def find(name, prefixes = nil, partial = nil, keys = nil, options = nil); end
  def find_all(name, prefixes = nil, partial = nil, keys = nil, options = nil); end
  def find_file(name, prefixes = nil, partial = nil, keys = nil, options = nil); end
  def find_template(name, prefixes = nil, partial = nil, keys = nil, options = nil); end
  def html_fallback_for_js; end
  def normalize_name(name, prefixes); end
  def template_exists?(name, prefixes = nil, partial = nil, keys = nil, **options); end
  def view_paths; end
  def view_paths=(paths); end
  def with_fallbacks; end
end
class ActionView::Template::Types
  def self.[](type); end
  def self.delegate_to(klass); end
  def self.symbols; end
  def self.type_klass; end
  def self.type_klass=(obj); end
  def type_klass; end
  def type_klass=(obj); end
end
class ActionView::Template::Types::Type
  def ==(type); end
  def initialize(symbol); end
  def ref; end
  def self.[](type); end
  def symbol; end
  def to_s; end
  def to_str; end
  def to_sym; end
end
class ActionView::PathSet
  def +(array); end
  def <<(*args); end
  def [](*args, &block); end
  def _find_all(path, prefixes, args, outside_app); end
  def compact; end
  def concat(*args); end
  def each(*args, &block); end
  def exists?(path, prefixes, *args); end
  def find(*args); end
  def find_all(path, prefixes = nil, *args); end
  def find_all_with_query(query); end
  def find_file(path, prefixes = nil, *args); end
  def include?(*args, &block); end
  def initialize(paths = nil); end
  def initialize_copy(other); end
  def insert(*args); end
  def paths; end
  def pop(*args, &block); end
  def push(*args); end
  def size(*args, &block); end
  def to_ary; end
  def typecast(paths); end
  def unshift(*args); end
  include Enumerable
end
class ActionView::DependencyTracker
  def self.find_dependencies(name, template, view_paths = nil); end
  def self.register_tracker(extension, tracker); end
  def self.remove_tracker(handler); end
end
class ActionView::DependencyTracker::ERBTracker
  def add_dependencies(render_dependencies, arguments, pattern); end
  def add_dynamic_dependency(dependencies, dependency); end
  def add_static_dependency(dependencies, dependency); end
  def dependencies; end
  def directory; end
  def explicit_dependencies; end
  def initialize(name, template, view_paths = nil); end
  def name; end
  def render_dependencies; end
  def resolve_directories(wildcard_dependencies); end
  def self.call(name, template, view_paths = nil); end
  def self.supports_view_paths?; end
  def source; end
  def template; end
end
class ActionView::Base
  def _routes; end
  def _routes=(val); end
  def _routes?; end
  def assign(new_assigns); end
  def assigns; end
  def assigns=(arg0); end
  def automatically_disable_submit_tag; end
  def automatically_disable_submit_tag=(obj); end
  def config; end
  def config=(arg0); end
  def debug_missing_translation; end
  def debug_missing_translation=(obj); end
  def default_formats; end
  def default_formats=(obj); end
  def field_error_proc; end
  def field_error_proc=(obj); end
  def formats(*args, &block); end
  def formats=(arg); end
  def initialize(context = nil, assigns = nil, controller = nil, formats = nil); end
  def locale(*args, &block); end
  def locale=(arg); end
  def logger; end
  def logger=(val); end
  def logger?; end
  def lookup_context(*args, &block); end
  def prefix_partial_path_with_controller_namespace; end
  def prefix_partial_path_with_controller_namespace=(obj); end
  def raise_on_missing_translations; end
  def raise_on_missing_translations=(obj); end
  def self._routes; end
  def self._routes=(val); end
  def self._routes?; end
  def self.automatically_disable_submit_tag; end
  def self.automatically_disable_submit_tag=(obj); end
  def self.cache_template_loading; end
  def self.cache_template_loading=(value); end
  def self.debug_missing_translation; end
  def self.debug_missing_translation=(obj); end
  def self.default_form_builder; end
  def self.default_form_builder=(obj); end
  def self.default_formats; end
  def self.default_formats=(obj); end
  def self.erb_trim_mode=(arg); end
  def self.field_error_proc; end
  def self.field_error_proc=(obj); end
  def self.logger; end
  def self.logger=(val); end
  def self.logger?; end
  def self.prefix_partial_path_with_controller_namespace; end
  def self.prefix_partial_path_with_controller_namespace=(obj); end
  def self.raise_on_missing_translations; end
  def self.raise_on_missing_translations=(obj); end
  def self.streaming_completion_on_exception; end
  def self.streaming_completion_on_exception=(obj); end
  def self.xss_safe?; end
  def streaming_completion_on_exception; end
  def streaming_completion_on_exception=(obj); end
  def view_paths(*args, &block); end
  def view_paths=(arg); end
  def view_renderer; end
  def view_renderer=(arg0); end
  extend ActionView::Helpers::SanitizeHelper::ClassMethods
  extend ActionView::Helpers::SanitizeHelper::ClassMethods
  extend ActionView::Helpers::UrlHelper::ClassMethods
  include ActionView::Helpers
  include ActionView::Helpers::AssetTagHelper
  include ActionView::Helpers::FormHelper
  include ActionView::Helpers::FormTagHelper
  include ActionView::Helpers::FormTagHelper
  include ActionView::Helpers::SanitizeHelper
  include ActionView::Helpers::SanitizeHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::TranslationHelper
  include ActionView::Helpers::UrlHelper
  include ActionView::Helpers::UrlHelper
  include ActionView::Helpers::UrlHelper
  include Kaminari::Helpers::HelperMethods
end
module ActionView::Helpers::Tags
  extend ActiveSupport::Autoload
end
module ActionView::Helpers::Tags::Placeholderable
  def initialize(*arg0); end
end
class ActionView::Helpers::Tags::Base
  def add_default_name_and_id(options); end
  def add_default_name_and_id_for_value(tag_value, options); end
  def add_options(option_tags, options, value = nil); end
  def generate_ids?; end
  def initialize(object_name, method_name, template_object, options = nil); end
  def name_and_id_index(options); end
  def object; end
  def placeholder_required?(html_options); end
  def render; end
  def retrieve_autoindex(pre_match); end
  def retrieve_object(object); end
  def sanitized_method_name; end
  def sanitized_object_name; end
  def sanitized_value(value); end
  def select_content_tag(option_tags, options, html_options); end
  def tag_id(index = nil); end
  def tag_name(multiple = nil, index = nil); end
  def value; end
  def value_before_type_cast; end
  def value_came_from_user?; end
  extend ActionView::Helpers::SanitizeHelper::ClassMethods
  extend ActionView::Helpers::UrlHelper::ClassMethods
  include ActionView::Helpers::ActiveModelInstanceTag
  include ActionView::Helpers::FormOptionsHelper
  include ActionView::Helpers::SanitizeHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::UrlHelper
end
class ActionView::Helpers::Tags::TextArea < ActionView::Helpers::Tags::Base
  def render; end
  include ActionView::Helpers::Tags::Placeholderable
end
class ActionView::Digestor
  def self.digest(name:, finder:, dependencies: nil); end
  def self.find_template(finder, name, prefixes, partial, keys); end
  def self.logger; end
  def self.tree(name, finder, partial = nil, seen = nil); end
end
module ActionView::Digestor::PerExecutionDigestCacheExpiry
  def self.before(target); end
end
class ActionView::Digestor::Node
  def children; end
  def dependency_digest(finder, stack); end
  def digest(finder, stack = nil); end
  def initialize(name, logical_name, template, children = nil); end
  def logical_name; end
  def name; end
  def self.create(name, logical_name, template, partial); end
  def template; end
  def to_dep_map; end
end
class ActionView::Digestor::Partial < ActionView::Digestor::Node
end
class ActionView::Digestor::Missing < ActionView::Digestor::Node
  def digest(finder, _ = nil); end
end
class ActionView::Digestor::Injected < ActionView::Digestor::Node
  def digest(finder, _ = nil); end
end
class ActionView::Digestor::NullLogger
  def self.debug(_); end
  def self.error(_); end
end
module ActionView::CollectionCaching
  def cache_collection_render(instrumentation_payload); end
  def callable_cache_key?; end
  def collection_by_cache_keys; end
  def expanded_cache_key(key); end
  def fetch_or_cache_partial(cached_partials, order_by:); end
  extend ActiveSupport::Concern
end
class ActionView::AbstractRenderer
  def any_templates?(*args, &block); end
  def extract_details(options); end
  def find_file(*args, &block); end
  def find_template(*args, &block); end
  def formats(*args, &block); end
  def initialize(lookup_context); end
  def instrument(name, **options); end
  def prepend_formats(formats); end
  def render; end
  def template_exists?(*args, &block); end
  def with_fallbacks(*args, &block); end
  def with_layout_format(*args, &block); end
end
class ActionView::PartialIteration
  def first?; end
  def index; end
  def initialize(size); end
  def iterate!; end
  def last?; end
  def size; end
end
class ActionView::PartialRenderer < ActionView::AbstractRenderer
  def collection_cache; end
  def collection_cache=(obj); end
  def collection_from_object; end
  def collection_from_options; end
  def collection_with_template; end
  def collection_without_template; end
  def find_partial; end
  def find_template(path, locals); end
  def initialize(*arg0); end
  def merge_prefix_into_object_path(prefix, object_path); end
  def partial_path(object = nil); end
  def prefixed_partial_names; end
  def raise_invalid_identifier(path); end
  def raise_invalid_option_as(as); end
  def render(context, options, block); end
  def render_collection; end
  def render_partial; end
  def retrieve_template_keys; end
  def retrieve_variable(path, as); end
  def self.collection_cache; end
  def self.collection_cache=(obj); end
  def setup(context, options, block); end
  include ActionView::CollectionCaching
end
module ActionView::ViewPaths
  def _prefixes; end
  def any_templates?(*args, &block); end
  def append_view_path(path); end
  def details_for_lookup; end
  def formats(*args, &block); end
  def formats=(arg); end
  def locale(*args, &block); end
  def locale=(arg); end
  def lookup_context; end
  def prepend_view_path(path); end
  def template_exists?(*args, &block); end
  def view_paths(*args, &block); end
  extend ActiveSupport::Concern
end
module ActionView::ViewPaths::ClassMethods
  def _prefixes; end
  def append_view_path(path); end
  def local_prefixes; end
  def prepend_view_path(path); end
  def view_paths; end
  def view_paths=(paths); end
end
class ActionView::I18nProxy < I18n::Config
  def initialize(original_config, lookup_context); end
  def locale; end
  def locale=(value); end
  def lookup_context; end
  def original_config; end
end
module ActionView::Rendering
  def _normalize_args(action = nil, options = nil); end
  def _normalize_options(options); end
  def _process_format(format); end
  def _render_template(options); end
  def process(*arg0); end
  def render_to_body(options = nil); end
  def rendered_format; end
  def view_context; end
  def view_context_class; end
  def view_context_class=(arg0); end
  def view_renderer; end
  extend ActiveSupport::Concern
  include ActionView::ViewPaths
end
module ActionView::Rendering::ClassMethods
  def view_context_class; end
end
module ActionView::Layouts
  def _conditional_layout?; end
  def _default_layout(formats, require_layout = nil); end
  def _include_layout?(options); end
  def _layout(*arg0); end
  def _layout_conditions(*args, &block); end
  def _layout_for_option(name); end
  def _normalize_layout(value); end
  def _normalize_options(options); end
  def action_has_layout=(arg0); end
  def action_has_layout?; end
  def initialize(*arg0); end
  extend ActiveSupport::Concern
  include ActionView::Rendering
end
module ActionView::Layouts::ClassMethods
  def _implied_layout_name; end
  def _write_layout_method; end
  def inherited(klass); end
  def layout(layout, conditions = nil); end
end
module ActionView::Layouts::ClassMethods::LayoutConditions
  def _conditional_layout?; end
end
module ActionView::RoutingUrlFor
  def _generate_paths_by_default; end
  def _routes_context; end
  def only_path?(host); end
  def optimize_routes_generation?; end
  def url_for(options = nil); end
  def url_options; end
end
