# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/acts_as_tree/all/acts_as_tree.rbi
#
# acts_as_tree-2.9.0
module ActsAsTree
  def self.included(base); end
end
class ActsAsTree::Railtie < Rails::Railtie
end
module ActiveRecord
end
module ActiveRecord::Acts
end
module ActiveRecord::Acts::Tree
  def self.included(base); end
  extend ActsAsTree::ClassMethods
  include ActsAsTree
end
module ActsAsTree::ClassMethods
  def acts_as_tree(options = nil); end
end
module ActsAsTree::TreeView
  def tree_view(label_method = nil, node = nil, level = nil); end
end
module ActsAsTree::TreeWalker
  def self.extended(mod); end
  def walk_tree(options = nil, &block); end
  def walk_tree_bfs(where = nil, node = nil, level = nil, &block); end
  def walk_tree_dfs(where = nil, node = nil, level = nil, &block); end
end
module ActsAsTree::InstanceMethods
  def ancestors; end
  def descendants; end
  def generation; end
  def leaf?; end
  def level; end
  def root; end
  def root?; end
  def self_and_ancestors; end
  def self_and_children; end
  def self_and_descendants; end
  def self_and_generation; end
  def self_and_siblings; end
  def siblings; end
  def tree_level; end
  def update_parents_counter_cache; end
end
