# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/codemirror-rails/all/codemirror-rails.rbi
#
# codemirror-rails-5.16.0
module Codemirror
end
module Codemirror::Rails
end
class Codemirror::Rails::Engine < Rails::Engine
end
