# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/cssmin/all/cssmin.rbi
#
# cssmin-1.0.3
module CSSMin
  def self.minify(input); end
end
