# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/erubis/all/erubis.rbi
#
# erubis-2.7.0
module Erubis
end
class Erubis::TinyEruby
  def convert(input); end
  def evaluate(_context = nil); end
  def initialize(input = nil); end
  def result(_binding = nil); end
  def src; end
end
module Erubis::PI
end
class Erubis::PI::TinyEruby
  def convert(input); end
  def evaluate(_context = nil); end
  def initialize(input = nil, options = nil); end
  def result(_binding = nil); end
  def src; end
end
