# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/escape_utils/all/escape_utils.rbi
#
# escape_utils-1.2.1
module EscapeUtils
  def escape_html(*arg0); end
  def escape_html_as_html_safe(arg0); end
  def escape_javascript(arg0); end
  def escape_uri(arg0); end
  def escape_uri_component(arg0); end
  def escape_url(arg0); end
  def escape_xml(arg0); end
  def self.html_safe_string_class; end
  def self.html_safe_string_class=(arg0); end
  def self.html_secure; end
  def self.html_secure=(arg0); end
  def unescape_html(arg0); end
  def unescape_javascript(arg0); end
  def unescape_uri(arg0); end
  def unescape_uri_component(arg0); end
  def unescape_url(arg0); end
  extend EscapeUtils
end
