# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/flipper-active_record/all/flipper-active_record.rbi
#
# flipper-active_record-0.16.2
module Flipper
end
module Flipper::Adapters
end
class Flipper::Adapters::ActiveRecord
  def add(feature); end
  def clear(feature); end
  def disable(feature, gate, thing); end
  def enable(feature, gate, thing); end
  def enable_multi(feature, gate, thing); end
  def enable_single(feature, gate, thing); end
  def features; end
  def get(feature); end
  def get_all; end
  def get_multi(features); end
  def initialize(options = nil); end
  def name; end
  def remove(feature); end
  def result_for_feature(feature, db_gates); end
  def unsupported_data_type(data_type); end
  extend Flipper::Adapter::ClassMethods
  include Flipper::Adapter
end
module Anonymous_ActiveRecord_AttributeMethods_GeneratedAttributeMethods_28
end
class Flipper::Adapters::ActiveRecord::Feature < ActiveRecord::Base
  def self._validators; end
  def self.attribute_type_decorations; end
  def self.defined_enums; end
  def self.page(num = nil); end
  extend Kaminari::ConfigurationMethods::ClassMethods
  include Anonymous_ActiveRecord_AttributeMethods_GeneratedAttributeMethods_28
  include Flipper::Adapters::ActiveRecord::Feature::GeneratedAssociationMethods
  include Kaminari::ActiveRecordModelExtension
  include Kaminari::ConfigurationMethods
end
module Flipper::Adapters::ActiveRecord::Feature::GeneratedAssociationMethods
end
class Flipper::Adapters::ActiveRecord::Feature::ActiveRecord_Relation < ActiveRecord::Relation
  extend ActiveRecord::Delegation::ClassSpecificRelation::ClassMethods
  include ActiveRecord::Delegation::ClassSpecificRelation
  include Flipper::Adapters::ActiveRecord::Feature::GeneratedRelationMethods
end
module Flipper::Adapters::ActiveRecord::Feature::GeneratedRelationMethods
end
class Flipper::Adapters::ActiveRecord::Feature::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
  extend ActiveRecord::Delegation::ClassSpecificRelation::ClassMethods
  include ActiveRecord::Delegation::ClassSpecificRelation
  include Flipper::Adapters::ActiveRecord::Feature::GeneratedRelationMethods
end
class Flipper::Adapters::ActiveRecord::Feature::ActiveRecord_AssociationRelation < ActiveRecord::AssociationRelation
  extend ActiveRecord::Delegation::ClassSpecificRelation::ClassMethods
  include ActiveRecord::Delegation::ClassSpecificRelation
  include Flipper::Adapters::ActiveRecord::Feature::GeneratedRelationMethods
end
module Anonymous_ActiveRecord_AttributeMethods_GeneratedAttributeMethods_29
end
class Flipper::Adapters::ActiveRecord::Gate < ActiveRecord::Base
  def self._validators; end
  def self.attribute_type_decorations; end
  def self.defined_enums; end
  def self.page(num = nil); end
  extend Kaminari::ConfigurationMethods::ClassMethods
  include Anonymous_ActiveRecord_AttributeMethods_GeneratedAttributeMethods_29
  include Flipper::Adapters::ActiveRecord::Gate::GeneratedAssociationMethods
  include Kaminari::ActiveRecordModelExtension
  include Kaminari::ConfigurationMethods
end
module Flipper::Adapters::ActiveRecord::Gate::GeneratedAssociationMethods
end
class Flipper::Adapters::ActiveRecord::Gate::ActiveRecord_Relation < ActiveRecord::Relation
  extend ActiveRecord::Delegation::ClassSpecificRelation::ClassMethods
  include ActiveRecord::Delegation::ClassSpecificRelation
  include Flipper::Adapters::ActiveRecord::Gate::GeneratedRelationMethods
end
module Flipper::Adapters::ActiveRecord::Gate::GeneratedRelationMethods
end
class Flipper::Adapters::ActiveRecord::Gate::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
  extend ActiveRecord::Delegation::ClassSpecificRelation::ClassMethods
  include ActiveRecord::Delegation::ClassSpecificRelation
  include Flipper::Adapters::ActiveRecord::Gate::GeneratedRelationMethods
end
class Flipper::Adapters::ActiveRecord::Gate::ActiveRecord_AssociationRelation < ActiveRecord::AssociationRelation
  extend ActiveRecord::Delegation::ClassSpecificRelation::ClassMethods
  include ActiveRecord::Delegation::ClassSpecificRelation
  include Flipper::Adapters::ActiveRecord::Gate::GeneratedRelationMethods
end
