# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/flot-rails/all/flot-rails.rbi
#
# flot-rails-0.0.7
module Flot
end
module Flot::Rails
end
class Flot::Rails::Engine < Rails::Engine
end
