# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/innertube/all/innertube.rbi
#
# innertube-1.1.0
module Innertube
end
class Innertube::Pool
  def >>(opts = nil); end
  def clear; end
  def close; end
  def delete_element(e); end
  def delete_if; end
  def each; end
  def each_element; end
  def fill(resources); end
  def initialize(open, close); end
  def size; end
  def take(opts = nil); end
end
class Innertube::Pool::BadResource < RuntimeError
end
class Innertube::Pool::Element
  def initialize(object); end
  def lock; end
  def locked?; end
  def object; end
  def owner; end
  def unlock; end
  def unlocked?; end
end
