# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/jquery-datatables/all/jquery-datatables.rbi
#
# jquery-datatables-1.10.19.1
module Jquery
end
module Jquery::Datatables
  def self.assets_path; end
  def self.gem_path; end
  def self.hanami?; end
  def self.javascripts_path; end
  def self.load!; end
  def self.rails?; end
  def self.register_hanami; end
  def self.register_rails_engine; end
  def self.register_sprockets; end
  def self.sprockets?; end
  def self.stylesheets_path; end
end
class Jquery::Datatables::Engine < Rails::Engine
end
