# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/jquery-rails/all/jquery-rails.rbi
#
# jquery-rails-4.3.5
module Jquery
end
module Jquery::Rails
end
class Jquery::Rails::Engine < Rails::Engine
end
