# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/metaclass/all/metaclass.rbi
#
# metaclass-0.0.4
module Metaclass
end
module Metaclass::ObjectMethods
  def __metaclass__; end
end
class Object < BasicObject
  include Metaclass::ObjectMethods
end
