# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/mousetrap-rails/all/mousetrap-rails.rbi
#
# mousetrap-rails-1.4.6
module Mousetrap
end
module Mousetrap::Rails
end
class Mousetrap::Rails::Engine < Rails::Engine
end
