# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/peek-dalli/all/peek-dalli.rbi
#
# peek-dalli-1.2.0
module Peek
end
module Peek::Dalli
end
module Peek::Views
end
class Peek::Views::Dalli < Peek::Views::View
  def context; end
  def formatted_duration; end
  def initialize(options = nil); end
  def results; end
  def setup_subscribers; end
end
class Peek::Dalli::Railtie < Rails::Engine
end
