# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rails_tokeninput/all/rails_tokeninput.rbi
#
# rails_tokeninput-1.7.0
module RailsTokeninput
end
module RailsTokeninput::Rails
end
class RailsTokeninput::Rails::Engine < Rails::Engine
end
