# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/redcarpet/all/redcarpet.rbi
#
# redcarpet-3.4.0
class Redcarpet::Markdown
  def render(arg0); end
  def renderer; end
  def self.new(*arg0); end
end
class Redcarpet::Render::Base
  def initialize; end
end
class Redcarpet::Render::HTML < Redcarpet::Render::Base
  def initialize(*arg0); end
end
class Redcarpet::Render::HTML_TOC < Redcarpet::Render::Base
  def initialize(*arg0); end
end
module Redcarpet::Render::SmartyPants
  def postprocess(arg0); end
  def self.render(text); end
  extend Redcarpet::Render::SmartyPants
end
class RedcarpetCompat
  def initialize(text, *exts); end
  def list_to_truthy_hash(list); end
  def parse_extensions_and_renderer_options(exts); end
  def rename_extensions(exts); end
  def text; end
  def text=(arg0); end
  def to_html(*_dummy); end
end
module Redcarpet
end
module Redcarpet::Render
end
class Redcarpet::Render::XHTML < Redcarpet::Render::HTML
  def initialize(extensions = nil); end
end
class Redcarpet::Render::SmartyHTML < Redcarpet::Render::HTML
  include Redcarpet::Render::SmartyPants
end
class Redcarpet::Render::Safe < Redcarpet::Render::HTML
  def block_code(code, lang); end
  def html_escape(string); end
  def initialize(extensions = nil); end
end
class Redcarpet::Render::StripDown < Redcarpet::Render::Base
  def autolink(*args); end
  def block_code(*args); end
  def block_html(*args); end
  def block_quote(*args); end
  def codespan(*args); end
  def double_emphasis(*args); end
  def emphasis(*args); end
  def entity(*args); end
  def footnote_def(*args); end
  def footnote_ref(*args); end
  def footnotes(*args); end
  def header(text, header_level); end
  def highlight(*args); end
  def image(link, title, content); end
  def link(link, title, content); end
  def list(*args); end
  def list_item(*args); end
  def normal_text(*args); end
  def paragraph(text); end
  def raw_html(*args); end
  def strikethrough(*args); end
  def superscript(*args); end
  def table(header, body); end
  def table_cell(content, alignment); end
  def table_row(content); end
  def triple_emphasis(*args); end
  def underline(*args); end
end
