# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rspec_junit_formatter/all/rspec_junit_formatter.rbi
#
# rspec_junit_formatter-0.4.1
class RSpecJUnitFormatter < RSpec::Core::Formatters::BaseFormatter
  def classname_for(notification); end
  def description_for(notification); end
  def dump_summary(notification); end
  def duration; end
  def duration_for(notification); end
  def escape(text); end
  def example_count; end
  def example_group_file_path_for(notification); end
  def examples; end
  def exception_for(notification); end
  def failure_count; end
  def failure_for(notification); end
  def failure_message_for(example); end
  def failure_type_for(example); end
  def pending_count; end
  def result_of(notification); end
  def start(notification); end
  def started; end
  def stderr_for(example_notification); end
  def stdout_for(example_notification); end
  def stop(notification); end
  def strip_diff_colors(string); end
  def swap_rspec_configuration(key, value); end
  def without_color(&block); end
  def xml_dump; end
  def xml_dump_example(example); end
  def xml_dump_examples; end
  def xml_dump_failed(example); end
  def xml_dump_output(example); end
  def xml_dump_pending(example); end
end
