# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/xmlhash/all/xmlhash.rbi
#
# xmlhash-1.3.7
module Xmlhash
  def self.parse(str); end
  def self.parse_int(arg0); end
end
class Xmlhash::XMLHash < Hash
  def elements(name); end
  def get(name); end
  def initialize(opts = nil); end
  def inspect; end
  def value(name); end
end
