#!/usr/bin/ruby

require 'optparse'
require 'rubygems'
require_gem 'builder'

require 'erb'
include ERB::Util

require "ftools"

require "rest.rb"
require "rest_test.rb"

class Options

  attr_accessor :verbose, :filename, :html, :outline, :output_dir,
    :create_template, :testfile, :force, :request, :show_all

  def initialize
    verbose = false
    html = false
  end

  def self.parse( args )
    options = Options.new

    opt = OptionParser.new

    opt.banner = "Usage: rest_test [options] filename"

    opt.on( "-h", "--help", "Print this message" ) do
      puts opt
      exit
    end

    opt.on( "-v", "--verbose", "Verbose mode" ) do
      options.verbose = true
    end

    opt.on( "--create-test", "Create test template" ) do
      options.create_template = true
    end

    opt.on( "--test=testfile", "Select test file" ) do |val|
      options.testfile = val
    end

    opt.on( "--force", "Force overwriting of test file" ) do
      options.force = true
    end

    opt.on( "--request=name", "Select request to be tested" ) do |val|
      options.request = val
    end

    opt.on( "--show-all", "Show all requests, not only non-passed." ) do
      options.show_all = true
    end

    begin
      opt.parse!( args )
    rescue OptionParser::InvalidOption
      puts $!
      puts opt
      exit
    end

    if ( ARGV.size > 1 )
      puts "Too many arguments"
      puts opt
      exit
    elsif ( ARGV.size < 1 )
      puts "Too few arguments"
      puts opt
      exit
    end

    options.filename = ARGV[0]

    options
  end

end

options = Options.parse( ARGV )

begin

  if ( !options.testfile )
    options.testfile = options.filename + ".test"
  end

  document = Document.new
  document.parse_args

  @requests = document.all_children Request

  if ( !File.exists?( options.testfile ) || options.create_template )
    if ( File.exists?( options.testfile ) )
      if ( !options.force )
        STDERR.puts "Test file '#{options.testfile} already exists." +
          " Use '--force' to overwrite it. Exiting."
        return
      end
      puts "Overwriting test file '#{options.testfile}'."
    else
      puts "Creating test file '#{options.testfile}'."
    end
    File.open( options.testfile, "w" ) do |file|
      @requests.each do |r|
        file.puts "request \"#{r}\""
      end
    end
  end
  
  runner = TestRunner.new @requests

  configfile = options.testfile + ".config"
  if ( File.exists? configfile )
    File.open configfile do |file|
      eval file.read, runner.context.get_binding
    end
  end

  if ( options.verbose )
    runner.context.show_xmlbody = true
  end
  runner.context.show_passed = options.show_all
  runner.context.request_filter = options.request

  runner.run options.testfile

rescue Errno::ENOENT
  puts $!
end
