#!/bin/bash

if [ -z $1 ]; then
    echo "Synopsis:"
    echo "  $0 <back|front|web>"
    exit 1
fi

case $1 in
    back|backend)
        SERVER_PATH=backend-dummy
        SERVER_PORT=42533
        ;;
    front|frontend)
        SERVER_PATH=frontend
        SERVER_PORT=42532
        ;;
    web|webclient)
        SERVER_PATH=webclient
        SERVER_PORT=42531
        ;;
esac

echo "Starting breakpointer for $SERVER_PATH on port $SERVER_PORT..."
pushd $SERVER_PATH
script/breakpointer -sdruby://localhost:$SERVER_PORT
popd
exit 0
