#!/bin/bash

if [ -z $1 ]; then
    echo "Synopsis:"
    echo "  $0 <back|back_test|front|web>"
    exit 1
fi

case $1 in
    back_test|backend_test)
        SERVER_PATH=backend-dummy
        SERVER_PORT=3003
        FLAGS='-e test'
        ;;
    back|backend)
        SERVER_PATH=backend-dummy
        SERVER_PORT=3002
        ;;
    front|frontend)
        SERVER_PATH=frontend
        SERVER_PORT=3001
        ;;
    front_test|frontend_test)
        SERVER_PATH=frontend
        FLAGS='-e test'
        SERVER_PORT=3001
        ;;
    web|webclient)
        SERVER_PATH=webclient
        SERVER_PORT=3000
        ;;
esac

echo "Starting $SERVER_PATH on port $SERVER_PORT..."
pushd $SERVER_PATH
script/server -p $SERVER_PORT $FLAGS
popd
exit 0
