production:
  features: &default
    image_templates: true
    kiwi_image_editor: false

development:
  features:
    <<: *default
    kiwi_image_editor: true

test:
  features:
    <<: *default
    kiwi_image_editor: true
