#!/bin/bash

DATADIR=${0%/*}

FAILS=""

#
# test constraints
#
function td()
{
  testname=$1
  expected=$2
  package=$3
  arch=$4
  worker=$DATADIR/workerinfo/$5
  srcconstraint=""
  prjconfconstraint=""
  [ -n "$6" ] && srcconstraint=$DATADIR/constraint/$6
  [ -n "$7" ] && prjconfconstraint=$DATADIR/constraintprj/$7
  if ./bs_dispatch --test-constraints "$package" "$arch" $worker "$srcconstraint" "$prjconfconstraint"; then
    if [ $expected != "true" ]; then
      echo "Failed for $package $arch $worker $srcconstraint $prjconfconstraint"
      FAILS="$FAILS $testname"
    fi
    echo -n .
  else
    if [ $? != "1" ]; then
      echo "CODE ERROR for $package $arch $worker $srcconstraint $prjconfconstraint"
      exit 2
    fi
    if [ $expected != "false" ]; then
      echo "Failed for $package $arch $worker $srcconstraint $prjconfconstraint"
      FAILS="$FAILS $testname"
    fi
    echo -n .
  fi
}

# simple source constraints for processor numbers and disk storage
td simple1 true "kernel" i586 large kernel
td simple2 false "kernel" i586 small kernel
td simple3 false "kernel" armv7l small kernel
td simple4 false "kernel-default" i586 small kernel
td simple5 false "kernel-default" armv7l small kernel
td simple6 false "kernel-default" aarch64 small kernel
td simple7 true "kernel-default" aarch64 medium kernel
td simple8 true "kernel-default" aarch64 large kernel

# simple prjconf constraints for processor numbers and disk storage
td simple11 true "kernel" i586 large "" kernel-default
td simple12 false "kernel" i586 small "" kernel-default
td simple13 false "kernel" armv7l small "" kernel-default
td simple14 false "kernel-default" i586 small "" kernel-default
td simple15 false "kernel-default" armv7l small "" kernel-default
td simple16 false "kernel-default" aarch64 small "" kernel-default
td simple17 false "kernel-default" aarch64 medium "" kernel-default
td simple18 true "kernel-default" aarch64 large "" kernel-default

# combined constraints for processor numbers and disk storage
td simple21 true "kernel" i586 large kernel kernel-default
td simple22 false "kernel" i586 small kernel kernel-default
td simple23 false "kernel" armv7l small kernel kernel-default
td simple24 false "kernel-default" i586 small kernel kernel-default
td simple25 false "kernel-default" armv7l small kernel kernel-default
td simple26 false "kernel-default" aarch64 small kernel kernel-default
td simple27 true "kernel-default" aarch64 medium kernel kernel-default
td simple28 true "kernel-default" aarch64 large kernel kernel-default

echo

if [ -n "$FAILS" ]; then
  echo "ERROR: Following test cases failed:"
  echo "$FAILS"
  exit 1
fi

exit 0

