#!/bin/bash

DATADIR=${0%/*}

#
# test constraints
#
function td()
{
  package=$2
  arch=$3
  worker=testdata/workerinfo/$4
  srcconstraint=""
  prjconfconstraint=""
  [ -n "$5" ] && srcconstraint=$DATADIR/$5
  [ -n "$6" ] && prjconfconstraint=$DATADIR/$6
  if ./bs_dispatch --test-constraints "$package" "$arch" $worker "$srcconstraint" "$prjconfconstraint"; then
    if [ $1 != "true" ]; then
      echo "Failed for $package $arch $worker $srcconstraint $prjconfconstraint"
      exit 1
    fi
    echo -n .
  else
    if [ $? != "1" ]; then
      echo "CODE ERROR for $package $arch $worker $srcconstraint $prjconfconstraint"
      exit 2
    fi
    if [ $1 != "false" ]; then
      echo "Failed for $package $arch $worker $srcconstraint $prjconfconstraint"
      exit 1
    fi
    echo -n .
  fi
}

# simple source constraints for processor numbers
td true "kernel" i586 large kernel
td false "kernel" i586 small kernel
td false "kernel" armv7l small kernel
td false "kernel-default" i586 small kernel
td true "kernel-default" armv7l small kernel
td false "kernel-default" aarch64 small kernel
td true "kernel-default" aarch64 medium kernel
td true "kernel-default" aarch64 large kernel

# simple prjconf constraints for processor numbers
td true "kernel" i586 large "" kernel-default
td false "kernel" i586 small "" kernel-default
td false "kernel" armv7l small "" kernel-default
td false "kernel-default" i586 small "" kernel-default
td false "kernel-default" armv7l small "" kernel-default
td false "kernel-default" aarch64 small "" kernel-default
td false "kernel-default" aarch64 medium "" kernel-default
td true "kernel-default" aarch64 large "" kernel-default

# combined constraints for processor numbers
td true "kernel" i586 large kernel kernel-default
td false "kernel" i586 small kernel kernel-default
td false "kernel" armv7l small kernel kernel-default
td false "kernel-default" i586 small kernel kernel-default
td false "kernel-default" armv7l small kernel kernel-default
td false "kernel-default" aarch64 small kernel kernel-default
td false "kernel-default" aarch64 medium kernel kernel-default
td true "kernel-default" aarch64 large kernel kernel-default

echo

