# Require all external libraries
require 'rubygems'
require 'tempfile'
require 'cgi'
require 'selenium-webdriver'

# Require all base AcceptanceTesting classes
require File.expand_path File.dirname(__FILE__) + '/common/ClassDeclarations'
require File.expand_path File.dirname(__FILE__) + '/common/Assertions'
require File.expand_path File.dirname(__FILE__) + '/common/WebDriver'
require File.expand_path File.dirname(__FILE__) + '/common/WebPage'
require File.expand_path File.dirname(__FILE__) + '/common/TestData'
require File.expand_path File.dirname(__FILE__) + '/common/TestCase'
require File.expand_path File.dirname(__FILE__) + '/common/HtmlReport'
require File.expand_path File.dirname(__FILE__) + '/common/TestRunner'

# Require all OBS page classes
require File.expand_path File.dirname(__FILE__) + '/OBSpages/BuildServicePage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/MainPage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/LoginPage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/SearchPage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/SearchResultsPage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/UserHomePage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/MyWorkPage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/MyProjectsPage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/MyRequestsPage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/RequestDetailsPage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/NewProjectPage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/NewPackagePage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/NewPackageBranchPage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/AllProjectsPage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/StatusMonitorPage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/ProjectPage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/ProjectPages/ProjectUsersPage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/ProjectPages/ProjectAddUserPage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/ProjectPages/ProjectAddGroupPage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/ProjectPages/ProjectConfigPage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/ProjectPages/ProjectStatusPage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/ProjectPages/ProjectOverviewPage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/ProjectPages/ProjectPackagesPage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/ProjectPages/ProjectRequestsPage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/ProjectPages/ProjectRawConfigPage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/ProjectPages/ProjectAttributesPage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/ProjectPages/ProjectSubprojectsPage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/ProjectPages/ProjectRepositoriesPage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/PackagePage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/PackagePages/PackageUsersPage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/PackagePages/PackageAddUserPage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/PackagePages/PackageAddGroupPage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/PackagePages/PackageAddFilePage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/PackagePages/PackageEditFilePage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/PackagePages/PackageSourcesPage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/PackagePages/PackageOverviewPage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/PackagePages/PackageRequestsPage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/PackagePages/PackageRawConfigPage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/PackagePages/PackageRevisionsPage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/PackagePages/PackageAttributesPage'
require File.expand_path File.dirname(__FILE__) + '/OBSpages/PackagePages/PackageRepositoriesPage'
